<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class LaraAuthAbilitiesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('lara_auth_abilities')->delete();
        
        \DB::table('lara_auth_abilities')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'view',
                'title' => 'Page view',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_key' => 'page',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'create',
                'title' => 'Page Create',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_key' => 'page',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => NULL,
                'updated_at' => '2017-11-02 15:02:24',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'update',
                'title' => 'Page update',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_key' => 'page',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'delete',
                'title' => 'Page delete',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Page',
                'entity_key' => 'page',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            4 => 
            array (
                'id' => 37,
                'name' => 'view',
                'title' => 'Slider view',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Slider',
                'entity_key' => 'slider',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2017-10-08 13:28:33',
                'updated_at' => '2017-10-08 13:28:33',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            5 => 
            array (
                'id' => 38,
                'name' => 'create',
                'title' => 'Slider create',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Slider',
                'entity_key' => 'slider',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2017-10-08 13:28:33',
                'updated_at' => '2017-10-08 13:28:33',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            6 => 
            array (
                'id' => 39,
                'name' => 'update',
                'title' => 'Slider update',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Slider',
                'entity_key' => 'slider',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2017-10-08 13:28:33',
                'updated_at' => '2017-10-08 13:28:33',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            7 => 
            array (
                'id' => 40,
                'name' => 'delete',
                'title' => 'Slider delete',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Slider',
                'entity_key' => 'slider',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2017-10-08 13:28:33',
                'updated_at' => '2017-10-08 13:28:33',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            8 => 
            array (
                'id' => 191,
                'name' => 'view',
                'title' => 'Cta view',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Cta',
                'entity_key' => 'cta',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2017-12-23 11:41:57',
                'updated_at' => '2017-12-23 11:41:57',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            9 => 
            array (
                'id' => 192,
                'name' => 'create',
                'title' => 'Cta create',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Cta',
                'entity_key' => 'cta',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2017-12-23 11:41:57',
                'updated_at' => '2017-12-23 11:41:57',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            10 => 
            array (
                'id' => 193,
                'name' => 'update',
                'title' => 'Cta update',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Cta',
                'entity_key' => 'cta',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2017-12-23 11:41:57',
                'updated_at' => '2017-12-23 11:41:57',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            11 => 
            array (
                'id' => 194,
                'name' => 'delete',
                'title' => 'Cta delete',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Cta',
                'entity_key' => 'cta',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2017-12-23 11:41:57',
                'updated_at' => '2017-12-23 11:41:57',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            12 => 
            array (
                'id' => 289,
                'name' => 'view',
                'title' => 'Blog view',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Blog',
                'entity_key' => 'blog',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-09-18 16:53:53',
                'updated_at' => '2018-09-18 16:53:53',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            13 => 
            array (
                'id' => 290,
                'name' => 'create',
                'title' => 'Blog create',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Blog',
                'entity_key' => 'blog',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-09-18 16:53:53',
                'updated_at' => '2018-09-18 16:53:53',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            14 => 
            array (
                'id' => 291,
                'name' => 'update',
                'title' => 'Blog update',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Blog',
                'entity_key' => 'blog',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-09-18 16:53:53',
                'updated_at' => '2018-09-18 16:53:53',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            15 => 
            array (
                'id' => 292,
                'name' => 'delete',
                'title' => 'Blog delete',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Blog',
                'entity_key' => 'blog',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-09-18 16:53:53',
                'updated_at' => '2018-09-18 16:53:53',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            16 => 
            array (
                'id' => 293,
                'name' => 'view',
                'title' => 'Team view',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Team',
                'entity_key' => 'team',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-09-18 17:13:48',
                'updated_at' => '2018-09-18 17:13:48',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            17 => 
            array (
                'id' => 294,
                'name' => 'create',
                'title' => 'Team create',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Team',
                'entity_key' => 'team',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-09-18 17:13:48',
                'updated_at' => '2018-09-18 17:13:48',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            18 => 
            array (
                'id' => 295,
                'name' => 'update',
                'title' => 'Team update',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Team',
                'entity_key' => 'team',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-09-18 17:13:48',
                'updated_at' => '2018-09-18 17:13:48',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            19 => 
            array (
                'id' => 296,
                'name' => 'delete',
                'title' => 'Team delete',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Team',
                'entity_key' => 'team',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-09-18 17:13:48',
                'updated_at' => '2018-09-18 17:13:48',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            20 => 
            array (
                'id' => 297,
                'name' => 'view',
                'title' => 'Event view',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Event',
                'entity_key' => 'event',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-11-14 16:03:40',
                'updated_at' => '2018-11-14 16:03:40',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            21 => 
            array (
                'id' => 298,
                'name' => 'create',
                'title' => 'Event create',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Event',
                'entity_key' => 'event',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-11-14 16:03:40',
                'updated_at' => '2018-11-14 16:03:40',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            22 => 
            array (
                'id' => 299,
                'name' => 'update',
                'title' => 'Event update',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Event',
                'entity_key' => 'event',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-11-14 16:03:40',
                'updated_at' => '2018-11-14 16:03:40',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            23 => 
            array (
                'id' => 300,
                'name' => 'delete',
                'title' => 'Event delete',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Event',
                'entity_key' => 'event',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-11-14 16:03:40',
                'updated_at' => '2018-11-14 16:03:40',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            24 => 
            array (
                'id' => 309,
                'name' => 'view',
                'title' => 'Location view',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Location',
                'entity_key' => 'location',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-11-29 15:19:02',
                'updated_at' => '2018-11-29 15:19:02',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            25 => 
            array (
                'id' => 310,
                'name' => 'create',
                'title' => 'Location create',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Location',
                'entity_key' => 'location',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-11-29 15:19:02',
                'updated_at' => '2018-11-29 15:19:02',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            26 => 
            array (
                'id' => 311,
                'name' => 'update',
                'title' => 'Location update',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Location',
                'entity_key' => 'location',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-11-29 15:19:02',
                'updated_at' => '2018-11-29 15:19:02',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            27 => 
            array (
                'id' => 312,
                'name' => 'delete',
                'title' => 'Location delete',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Location',
                'entity_key' => 'location',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-11-29 15:19:02',
                'updated_at' => '2018-11-29 15:19:02',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            28 => 
            array (
                'id' => 313,
                'name' => 'view',
                'title' => 'Portfolio view',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Portfolio',
                'entity_key' => 'portfolio',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-11-29 15:19:24',
                'updated_at' => '2018-11-29 15:19:24',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            29 => 
            array (
                'id' => 314,
                'name' => 'create',
                'title' => 'Portfolio create',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Portfolio',
                'entity_key' => 'portfolio',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-11-29 15:19:24',
                'updated_at' => '2018-11-29 15:19:24',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            30 => 
            array (
                'id' => 315,
                'name' => 'update',
                'title' => 'Portfolio update',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Portfolio',
                'entity_key' => 'portfolio',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-11-29 15:19:24',
                'updated_at' => '2018-11-29 15:19:24',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            31 => 
            array (
                'id' => 316,
                'name' => 'delete',
                'title' => 'Portfolio delete',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Portfolio',
                'entity_key' => 'portfolio',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-11-29 15:19:24',
                'updated_at' => '2018-11-29 15:19:24',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            32 => 
            array (
                'id' => 321,
                'name' => 'view',
                'title' => 'Product view',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Product',
                'entity_key' => 'product',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-11-29 15:19:50',
                'updated_at' => '2018-11-29 15:19:50',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            33 => 
            array (
                'id' => 322,
                'name' => 'create',
                'title' => 'Product create',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Product',
                'entity_key' => 'product',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-11-29 15:19:50',
                'updated_at' => '2018-11-29 15:19:50',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            34 => 
            array (
                'id' => 323,
                'name' => 'update',
                'title' => 'Product update',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Product',
                'entity_key' => 'product',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-11-29 15:19:50',
                'updated_at' => '2018-11-29 15:19:50',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            35 => 
            array (
                'id' => 324,
                'name' => 'delete',
                'title' => 'Product delete',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Product',
                'entity_key' => 'product',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-11-29 15:19:50',
                'updated_at' => '2018-11-29 15:19:50',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            36 => 
            array (
                'id' => 325,
                'name' => 'view',
                'title' => 'Doc view',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Doc',
                'entity_key' => 'doc',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-11-29 15:20:14',
                'updated_at' => '2018-11-29 15:20:14',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            37 => 
            array (
                'id' => 326,
                'name' => 'create',
                'title' => 'Doc create',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Doc',
                'entity_key' => 'doc',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-11-29 15:20:14',
                'updated_at' => '2018-11-29 15:20:14',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            38 => 
            array (
                'id' => 327,
                'name' => 'update',
                'title' => 'Doc update',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Doc',
                'entity_key' => 'doc',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-11-29 15:20:14',
                'updated_at' => '2018-11-29 15:20:14',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            39 => 
            array (
                'id' => 328,
                'name' => 'delete',
                'title' => 'Doc delete',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Doc',
                'entity_key' => 'doc',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-11-29 15:20:14',
                'updated_at' => '2018-11-29 15:20:14',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            40 => 
            array (
                'id' => 333,
                'name' => 'view',
                'title' => 'Gallery view',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Gallery',
                'entity_key' => 'gallery',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-11-29 15:21:06',
                'updated_at' => '2018-11-29 15:21:06',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            41 => 
            array (
                'id' => 334,
                'name' => 'create',
                'title' => 'Gallery create',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Gallery',
                'entity_key' => 'gallery',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-11-29 15:21:06',
                'updated_at' => '2018-11-29 15:21:06',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            42 => 
            array (
                'id' => 335,
                'name' => 'update',
                'title' => 'Gallery update',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Gallery',
                'entity_key' => 'gallery',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-11-29 15:21:06',
                'updated_at' => '2018-11-29 15:21:06',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            43 => 
            array (
                'id' => 336,
                'name' => 'delete',
                'title' => 'Gallery delete',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Gallery',
                'entity_key' => 'gallery',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-11-29 15:21:06',
                'updated_at' => '2018-11-29 15:21:06',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            44 => 
            array (
                'id' => 337,
                'name' => 'view',
                'title' => 'Video view',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Video',
                'entity_key' => 'video',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-11-29 15:21:21',
                'updated_at' => '2018-11-29 15:21:21',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            45 => 
            array (
                'id' => 338,
                'name' => 'create',
                'title' => 'Video create',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Video',
                'entity_key' => 'video',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-11-29 15:21:21',
                'updated_at' => '2018-11-29 15:21:21',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            46 => 
            array (
                'id' => 339,
                'name' => 'update',
                'title' => 'Video update',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Video',
                'entity_key' => 'video',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-11-29 15:21:21',
                'updated_at' => '2018-11-29 15:21:21',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            47 => 
            array (
                'id' => 340,
                'name' => 'delete',
                'title' => 'Video delete',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Video',
                'entity_key' => 'video',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2018-11-29 15:21:21',
                'updated_at' => '2018-11-29 15:21:21',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            48 => 
            array (
                'id' => 385,
                'name' => 'view',
                'title' => 'Contactform view',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Contactform',
                'entity_key' => 'contactform',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-02-06 16:29:45',
                'updated_at' => '2019-02-06 16:29:45',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            49 => 
            array (
                'id' => 386,
                'name' => 'create',
                'title' => 'Contactform create',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Contactform',
                'entity_key' => 'contactform',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-02-06 16:29:45',
                'updated_at' => '2019-02-06 16:29:45',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            50 => 
            array (
                'id' => 387,
                'name' => 'update',
                'title' => 'Contactform update',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Contactform',
                'entity_key' => 'contactform',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-02-06 16:29:45',
                'updated_at' => '2019-02-06 16:29:45',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            51 => 
            array (
                'id' => 388,
                'name' => 'delete',
                'title' => 'Contactform delete',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Contactform',
                'entity_key' => 'contactform',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-02-06 16:29:45',
                'updated_at' => '2019-02-06 16:29:45',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            52 => 
            array (
                'id' => 421,
                'name' => 'view',
                'title' => 'Setting view',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Setting',
                'entity_key' => 'setting',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-14 14:44:50',
                'updated_at' => '2019-07-14 14:44:50',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            53 => 
            array (
                'id' => 422,
                'name' => 'create',
                'title' => 'Setting create',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Setting',
                'entity_key' => 'setting',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-14 14:44:50',
                'updated_at' => '2019-07-14 14:44:50',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            54 => 
            array (
                'id' => 423,
                'name' => 'update',
                'title' => 'Setting update',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Setting',
                'entity_key' => 'setting',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-14 14:44:50',
                'updated_at' => '2019-07-14 14:44:50',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            55 => 
            array (
                'id' => 424,
                'name' => 'delete',
                'title' => 'Setting delete',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Setting',
                'entity_key' => 'setting',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-14 14:44:50',
                'updated_at' => '2019-07-14 14:44:50',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            56 => 
            array (
                'id' => 425,
                'name' => 'view',
                'title' => 'Translation view',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Translation',
                'entity_key' => 'translation',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-14 14:44:51',
                'updated_at' => '2019-07-14 14:44:51',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            57 => 
            array (
                'id' => 426,
                'name' => 'create',
                'title' => 'Translation create',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Translation',
                'entity_key' => 'translation',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-14 14:44:51',
                'updated_at' => '2019-07-14 14:44:51',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            58 => 
            array (
                'id' => 427,
                'name' => 'update',
                'title' => 'Translation update',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Translation',
                'entity_key' => 'translation',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-14 14:44:51',
                'updated_at' => '2019-07-14 14:44:51',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            59 => 
            array (
                'id' => 428,
                'name' => 'delete',
                'title' => 'Translation delete',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Translation',
                'entity_key' => 'translation',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-14 14:44:51',
                'updated_at' => '2019-07-14 14:44:51',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            60 => 
            array (
                'id' => 429,
                'name' => 'view',
                'title' => 'Menuitem view',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Menuitem',
                'entity_key' => 'menuitem',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-14 15:36:10',
                'updated_at' => '2019-07-14 15:36:10',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            61 => 
            array (
                'id' => 430,
                'name' => 'create',
                'title' => 'Menuitem create',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Menuitem',
                'entity_key' => 'menuitem',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-14 15:36:10',
                'updated_at' => '2019-07-14 15:36:10',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            62 => 
            array (
                'id' => 431,
                'name' => 'update',
                'title' => 'Menuitem update',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Menuitem',
                'entity_key' => 'menuitem',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-14 15:36:10',
                'updated_at' => '2019-07-14 15:36:10',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            63 => 
            array (
                'id' => 432,
                'name' => 'delete',
                'title' => 'Menuitem delete',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Menuitem',
                'entity_key' => 'menuitem',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-14 15:36:10',
                'updated_at' => '2019-07-14 15:36:10',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            64 => 
            array (
                'id' => 433,
                'name' => 'view',
                'title' => 'Seo view',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Seo',
                'entity_key' => 'seo',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-16 20:18:11',
                'updated_at' => '2019-07-16 20:18:11',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            65 => 
            array (
                'id' => 434,
                'name' => 'create',
                'title' => 'Seo create',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Seo',
                'entity_key' => 'seo',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-16 20:18:11',
                'updated_at' => '2019-07-16 20:18:11',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            66 => 
            array (
                'id' => 435,
                'name' => 'update',
                'title' => 'Seo update',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Seo',
                'entity_key' => 'seo',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-16 20:18:11',
                'updated_at' => '2019-07-16 20:18:11',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            67 => 
            array (
                'id' => 436,
                'name' => 'delete',
                'title' => 'Seo delete',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Seo',
                'entity_key' => 'seo',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-16 20:18:11',
                'updated_at' => '2019-07-16 20:18:11',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            68 => 
            array (
                'id' => 437,
                'name' => 'view',
                'title' => 'User view',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\User',
                'entity_key' => 'user',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-16 20:19:21',
                'updated_at' => '2019-07-16 20:19:21',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            69 => 
            array (
                'id' => 438,
                'name' => 'create',
                'title' => 'User create',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\User',
                'entity_key' => 'user',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-16 20:19:21',
                'updated_at' => '2019-07-16 20:19:21',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            70 => 
            array (
                'id' => 439,
                'name' => 'update',
                'title' => 'User update',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\User',
                'entity_key' => 'user',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-16 20:19:21',
                'updated_at' => '2019-07-16 20:19:21',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            71 => 
            array (
                'id' => 440,
                'name' => 'delete',
                'title' => 'User delete',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\User',
                'entity_key' => 'user',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-16 20:19:21',
                'updated_at' => '2019-07-16 20:19:21',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            72 => 
            array (
                'id' => 441,
                'name' => 'view',
                'title' => 'Redirect view',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Redirect',
                'entity_key' => 'redirect',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-16 20:31:17',
                'updated_at' => '2019-07-16 20:31:17',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            73 => 
            array (
                'id' => 442,
                'name' => 'create',
                'title' => 'Redirect create',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Redirect',
                'entity_key' => 'redirect',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-16 20:31:17',
                'updated_at' => '2019-07-16 20:31:17',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            74 => 
            array (
                'id' => 443,
                'name' => 'update',
                'title' => 'Redirect update',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Redirect',
                'entity_key' => 'redirect',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-16 20:31:17',
                'updated_at' => '2019-07-16 20:31:17',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            75 => 
            array (
                'id' => 444,
                'name' => 'delete',
                'title' => 'Redirect delete',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Redirect',
                'entity_key' => 'redirect',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-16 20:31:17',
                'updated_at' => '2019-07-16 20:31:17',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            76 => 
            array (
                'id' => 449,
                'name' => 'view',
                'title' => 'Language view',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Language',
                'entity_key' => 'language',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-17 19:52:26',
                'updated_at' => '2019-07-17 19:52:26',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            77 => 
            array (
                'id' => 450,
                'name' => 'create',
                'title' => 'Language create',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Language',
                'entity_key' => 'language',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-17 19:52:27',
                'updated_at' => '2019-07-17 19:52:27',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            78 => 
            array (
                'id' => 451,
                'name' => 'update',
                'title' => 'Language update',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Language',
                'entity_key' => 'language',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-17 19:52:27',
                'updated_at' => '2019-07-17 19:52:27',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            79 => 
            array (
                'id' => 452,
                'name' => 'delete',
                'title' => 'Language delete',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Language',
                'entity_key' => 'language',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-17 19:52:27',
                'updated_at' => '2019-07-17 19:52:27',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            80 => 
            array (
                'id' => 453,
                'name' => 'view',
                'title' => 'Tag view',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Tag',
                'entity_key' => 'tag',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-18 20:39:53',
                'updated_at' => '2019-07-18 20:39:53',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            81 => 
            array (
                'id' => 454,
                'name' => 'create',
                'title' => 'Tag create',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Tag',
                'entity_key' => 'tag',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-18 20:39:53',
                'updated_at' => '2019-07-18 20:39:53',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            82 => 
            array (
                'id' => 455,
                'name' => 'update',
                'title' => 'Tag update',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Tag',
                'entity_key' => 'tag',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-18 20:39:53',
                'updated_at' => '2019-07-18 20:39:53',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            83 => 
            array (
                'id' => 456,
                'name' => 'delete',
                'title' => 'Tag delete',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Tag',
                'entity_key' => 'tag',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-18 20:39:53',
                'updated_at' => '2019-07-18 20:39:53',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            84 => 
            array (
                'id' => 457,
                'name' => 'view',
                'title' => 'Menu view',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Menu',
                'entity_key' => 'menu',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-20 11:57:09',
                'updated_at' => '2019-07-20 11:57:09',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            85 => 
            array (
                'id' => 458,
                'name' => 'create',
                'title' => 'Menu create',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Menu',
                'entity_key' => 'menu',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-20 11:57:09',
                'updated_at' => '2019-07-20 11:57:09',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            86 => 
            array (
                'id' => 459,
                'name' => 'update',
                'title' => 'Menu update',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Menu',
                'entity_key' => 'menu',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-20 11:57:09',
                'updated_at' => '2019-07-20 11:57:09',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            87 => 
            array (
                'id' => 460,
                'name' => 'delete',
                'title' => 'Menu delete',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Menu',
                'entity_key' => 'menu',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-07-20 11:57:10',
                'updated_at' => '2019-07-20 11:57:10',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            88 => 
            array (
                'id' => 461,
                'name' => 'view',
                'title' => 'Larawidget view',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Larawidget',
                'entity_key' => 'larawidget',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-08-09 13:42:13',
                'updated_at' => '2019-08-09 13:42:13',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            89 => 
            array (
                'id' => 462,
                'name' => 'create',
                'title' => 'Larawidget create',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Larawidget',
                'entity_key' => 'larawidget',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-08-09 13:42:13',
                'updated_at' => '2019-08-09 13:42:13',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            90 => 
            array (
                'id' => 463,
                'name' => 'update',
                'title' => 'Larawidget update',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Larawidget',
                'entity_key' => 'larawidget',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-08-09 13:42:13',
                'updated_at' => '2019-08-09 13:42:13',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            91 => 
            array (
                'id' => 464,
                'name' => 'delete',
                'title' => 'Larawidget delete',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Larawidget',
                'entity_key' => 'larawidget',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-08-09 13:42:13',
                'updated_at' => '2019-08-09 13:42:13',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            92 => 
            array (
                'id' => 465,
                'name' => 'view',
                'title' => 'Sponsor view',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Sponsor',
                'entity_key' => 'sponsor',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-08-12 16:08:11',
                'updated_at' => '2019-08-12 16:08:11',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            93 => 
            array (
                'id' => 466,
                'name' => 'create',
                'title' => 'Sponsor create',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Sponsor',
                'entity_key' => 'sponsor',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-08-12 16:08:11',
                'updated_at' => '2019-08-12 16:08:11',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            94 => 
            array (
                'id' => 467,
                'name' => 'update',
                'title' => 'Sponsor update',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Sponsor',
                'entity_key' => 'sponsor',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-08-12 16:08:11',
                'updated_at' => '2019-08-12 16:08:11',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            95 => 
            array (
                'id' => 468,
                'name' => 'delete',
                'title' => 'Sponsor delete',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Sponsor',
                'entity_key' => 'sponsor',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-08-12 16:08:11',
                'updated_at' => '2019-08-12 16:08:11',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            96 => 
            array (
                'id' => 469,
                'name' => 'view',
                'title' => 'Classicform view',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Classicform',
                'entity_key' => 'classicform',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-12-17 09:27:50',
                'updated_at' => '2019-12-17 09:27:50',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            97 => 
            array (
                'id' => 470,
                'name' => 'create',
                'title' => 'Classicform create',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Classicform',
                'entity_key' => 'classicform',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-12-17 09:27:50',
                'updated_at' => '2019-12-17 09:27:50',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            98 => 
            array (
                'id' => 471,
                'name' => 'update',
                'title' => 'Classicform update',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Classicform',
                'entity_key' => 'classicform',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-12-17 09:27:50',
                'updated_at' => '2019-12-17 09:27:50',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            99 => 
            array (
                'id' => 472,
                'name' => 'delete',
                'title' => 'Classicform delete',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Classicform',
                'entity_key' => 'classicform',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2019-12-17 09:27:50',
                'updated_at' => '2019-12-17 09:27:50',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            100 => 
            array (
                'id' => 473,
                'name' => 'view',
                'title' => 'Story view',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Story',
                'entity_key' => 'story',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2020-06-17 16:31:52',
                'updated_at' => '2020-06-17 16:31:52',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            101 => 
            array (
                'id' => 474,
                'name' => 'create',
                'title' => 'Story create',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Story',
                'entity_key' => 'story',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2020-06-17 16:31:52',
                'updated_at' => '2020-06-17 16:31:52',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            102 => 
            array (
                'id' => 475,
                'name' => 'update',
                'title' => 'Story update',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Story',
                'entity_key' => 'story',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2020-06-17 16:31:52',
                'updated_at' => '2020-06-17 16:31:52',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            103 => 
            array (
                'id' => 476,
                'name' => 'delete',
                'title' => 'Story delete',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Story',
                'entity_key' => 'story',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2020-06-17 16:31:52',
                'updated_at' => '2020-06-17 16:31:52',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            104 => 
            array (
                'id' => 477,
                'name' => 'view',
                'title' => 'Testimonial view',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Testimonial',
                'entity_key' => 'testimonial',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2020-06-25 09:58:26',
                'updated_at' => '2020-06-25 09:58:26',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            105 => 
            array (
                'id' => 478,
                'name' => 'create',
                'title' => 'Testimonial create',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Testimonial',
                'entity_key' => 'testimonial',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2020-06-25 09:58:26',
                'updated_at' => '2020-06-25 09:58:26',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            106 => 
            array (
                'id' => 479,
                'name' => 'update',
                'title' => 'Testimonial update',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Testimonial',
                'entity_key' => 'testimonial',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2020-06-25 09:58:26',
                'updated_at' => '2020-06-25 09:58:26',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            107 => 
            array (
                'id' => 480,
                'name' => 'delete',
                'title' => 'Testimonial delete',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Testimonial',
                'entity_key' => 'testimonial',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2020-06-25 09:58:26',
                'updated_at' => '2020-06-25 09:58:26',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            108 => 
            array (
                'id' => 481,
                'name' => 'view',
                'title' => 'City view',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\City',
                'entity_key' => 'city',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2020-12-23 10:22:27',
                'updated_at' => '2020-12-23 10:22:27',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            109 => 
            array (
                'id' => 482,
                'name' => 'create',
                'title' => 'City create',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\City',
                'entity_key' => 'city',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2020-12-23 10:22:27',
                'updated_at' => '2020-12-23 10:22:27',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            110 => 
            array (
                'id' => 483,
                'name' => 'update',
                'title' => 'City update',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\City',
                'entity_key' => 'city',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2020-12-23 10:22:27',
                'updated_at' => '2020-12-23 10:22:27',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            111 => 
            array (
                'id' => 484,
                'name' => 'delete',
                'title' => 'City delete',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\City',
                'entity_key' => 'city',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2020-12-23 10:22:27',
                'updated_at' => '2020-12-23 10:22:27',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            112 => 
            array (
                'id' => 485,
                'name' => 'view',
                'title' => 'Service view',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Service',
                'entity_key' => 'service',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2023-03-11 14:10:05',
                'updated_at' => '2023-03-11 14:10:05',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            113 => 
            array (
                'id' => 486,
                'name' => 'create',
                'title' => 'Service create',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Service',
                'entity_key' => 'service',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2023-03-11 14:10:05',
                'updated_at' => '2023-03-11 14:10:05',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            114 => 
            array (
                'id' => 487,
                'name' => 'update',
                'title' => 'Service update',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Service',
                'entity_key' => 'service',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2023-03-11 14:10:05',
                'updated_at' => '2023-03-11 14:10:05',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            115 => 
            array (
                'id' => 488,
                'name' => 'delete',
                'title' => 'Service delete',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Service',
                'entity_key' => 'service',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2023-03-11 14:10:05',
                'updated_at' => '2023-03-11 14:10:05',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            116 => 
            array (
                'id' => 489,
                'name' => 'view',
                'title' => 'Headertag view',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Headertag',
                'entity_key' => 'headertag',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2024-03-01 11:01:35',
                'updated_at' => '2024-03-01 11:01:35',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            117 => 
            array (
                'id' => 490,
                'name' => 'create',
                'title' => 'Headertag create',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Headertag',
                'entity_key' => 'headertag',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2024-03-01 11:01:35',
                'updated_at' => '2024-03-01 11:01:35',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            118 => 
            array (
                'id' => 491,
                'name' => 'update',
                'title' => 'Headertag update',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Headertag',
                'entity_key' => 'headertag',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2024-03-01 11:01:35',
                'updated_at' => '2024-03-01 11:01:35',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            119 => 
            array (
                'id' => 492,
                'name' => 'delete',
                'title' => 'Headertag delete',
                'entity_id' => NULL,
                'entity_type' => 'Lara\\Common\\Models\\Headertag',
                'entity_key' => 'headertag',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2024-03-01 11:01:35',
                'updated_at' => '2024-03-01 11:01:35',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            120 => 
            array (
                'id' => 493,
                'name' => 'view',
                'title' => 'Cal view',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Cal',
                'entity_key' => 'cal',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2024-10-24 16:18:48',
                'updated_at' => '2024-10-24 16:18:48',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            121 => 
            array (
                'id' => 494,
                'name' => 'create',
                'title' => 'Cal create',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Cal',
                'entity_key' => 'cal',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2024-10-24 16:18:48',
                'updated_at' => '2024-10-24 16:18:48',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            122 => 
            array (
                'id' => 495,
                'name' => 'update',
                'title' => 'Cal update',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Cal',
                'entity_key' => 'cal',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2024-10-24 16:18:48',
                'updated_at' => '2024-10-24 16:18:48',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            123 => 
            array (
                'id' => 496,
                'name' => 'delete',
                'title' => 'Cal delete',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Cal',
                'entity_key' => 'cal',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2024-10-24 16:18:48',
                'updated_at' => '2024-10-24 16:18:48',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            124 => 
            array (
                'id' => 497,
                'name' => 'view',
                'title' => 'Loc view',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Loc',
                'entity_key' => 'loc',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2024-10-24 16:20:36',
                'updated_at' => '2024-10-24 16:20:36',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            125 => 
            array (
                'id' => 498,
                'name' => 'create',
                'title' => 'Loc create',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Loc',
                'entity_key' => 'loc',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2024-10-24 16:20:36',
                'updated_at' => '2024-10-24 16:20:36',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            126 => 
            array (
                'id' => 499,
                'name' => 'update',
                'title' => 'Loc update',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Loc',
                'entity_key' => 'loc',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2024-10-24 16:20:36',
                'updated_at' => '2024-10-24 16:20:36',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            127 => 
            array (
                'id' => 500,
                'name' => 'delete',
                'title' => 'Loc delete',
                'entity_id' => NULL,
                'entity_type' => 'Eve\\Models\\Loc',
                'entity_key' => 'loc',
                'only_owned' => 0,
                'options' => NULL,
                'scope' => NULL,
                'created_at' => '2024-10-24 16:20:36',
                'updated_at' => '2024-10-24 16:20:36',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
        ));
        
        
    }
}