<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class LaraEntEntityColumnsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('lara_ent_entity_columns')->delete();
        
        \DB::table('lara_ent_entity_columns')->insert(array (
            0 => 
            array (
                'id' => 2,
                'entity_id' => 1,
                'has_user' => 1,
                'has_lang' => 1,
                'has_slug' => 1,
                'has_lead' => 1,
                'has_body' => 1,
                'has_status' => 1,
                'has_hideinlist' => 0,
                'has_expiration' => 0,
                'has_app' => 1,
                'has_groups' => 1,
                'group_values' => 'page, module, email',
                'group_default' => 'page',
                'is_sortable' => 1,
                'sort_field' => 'position',
                'sort_order' => 'asc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 1,
            ),
            1 => 
            array (
                'id' => 3,
                'entity_id' => 2,
                'has_user' => 1,
                'has_lang' => 1,
                'has_slug' => 1,
                'has_lead' => 1,
                'has_body' => 1,
                'has_status' => 1,
                'has_hideinlist' => 1,
                'has_expiration' => 1,
                'has_app' => 0,
                'has_groups' => 0,
                'group_values' => NULL,
                'group_default' => NULL,
                'is_sortable' => 0,
                'sort_field' => 'created_at',
                'sort_order' => 'desc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 1,
            ),
            2 => 
            array (
                'id' => 4,
                'entity_id' => 3,
                'has_user' => 1,
                'has_lang' => 1,
                'has_slug' => 1,
                'has_lead' => 0,
                'has_body' => 1,
                'has_status' => 1,
                'has_hideinlist' => 1,
                'has_expiration' => 0,
                'has_app' => 0,
                'has_groups' => 0,
                'group_values' => NULL,
                'group_default' => NULL,
                'is_sortable' => 1,
                'sort_field' => 'position',
                'sort_order' => 'asc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 1,
            ),
            3 => 
            array (
                'id' => 11,
                'entity_id' => 17,
                'has_user' => 1,
                'has_lang' => 1,
                'has_slug' => 1,
                'has_lead' => 1,
                'has_body' => 1,
                'has_status' => 1,
                'has_hideinlist' => 1,
                'has_expiration' => 0,
                'has_app' => 0,
                'has_groups' => 0,
                'group_values' => NULL,
                'group_default' => NULL,
                'is_sortable' => 0,
                'sort_field' => 'startdate',
                'sort_order' => 'asc',
                'sort2_field' => 'starttime',
                'sort2_order' => 'asc',
                'has_fields' => 1,
            ),
            4 => 
            array (
                'id' => 12,
                'entity_id' => 18,
                'has_user' => 1,
                'has_lang' => 1,
                'has_slug' => 1,
                'has_lead' => 0,
                'has_body' => 0,
                'has_status' => 1,
                'has_hideinlist' => 1,
                'has_expiration' => 0,
                'has_app' => 0,
                'has_groups' => 0,
                'group_values' => NULL,
                'group_default' => NULL,
                'is_sortable' => 0,
                'sort_field' => 'id',
                'sort_order' => 'asc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 1,
            ),
            5 => 
            array (
                'id' => 14,
                'entity_id' => 20,
                'has_user' => 1,
                'has_lang' => 1,
                'has_slug' => 1,
                'has_lead' => 0,
                'has_body' => 0,
                'has_status' => 1,
                'has_hideinlist' => 0,
                'has_expiration' => 0,
                'has_app' => 0,
                'has_groups' => 0,
                'group_values' => NULL,
                'group_default' => NULL,
                'is_sortable' => 1,
                'sort_field' => 'position',
                'sort_order' => 'asc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 1,
            ),
            6 => 
            array (
                'id' => 19,
                'entity_id' => 27,
                'has_user' => 1,
                'has_lang' => 1,
                'has_slug' => 1,
                'has_lead' => 0,
                'has_body' => 1,
                'has_status' => 1,
                'has_hideinlist' => 0,
                'has_expiration' => 0,
                'has_app' => 0,
                'has_groups' => 0,
                'group_values' => NULL,
                'group_default' => NULL,
                'is_sortable' => 0,
                'sort_field' => 'hook',
                'sort_order' => 'asc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 1,
            ),
            7 => 
            array (
                'id' => 20,
                'entity_id' => 29,
                'has_user' => 1,
                'has_lang' => 1,
                'has_slug' => 1,
                'has_lead' => 0,
                'has_body' => 1,
                'has_status' => 1,
                'has_hideinlist' => 1,
                'has_expiration' => 0,
                'has_app' => 0,
                'has_groups' => 0,
                'group_values' => NULL,
                'group_default' => NULL,
                'is_sortable' => 1,
                'sort_field' => 'position',
                'sort_order' => 'asc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 1,
            ),
            8 => 
            array (
                'id' => 22,
                'entity_id' => 31,
                'has_user' => 1,
                'has_lang' => 1,
                'has_slug' => 1,
                'has_lead' => 0,
                'has_body' => 1,
                'has_status' => 1,
                'has_hideinlist' => 0,
                'has_expiration' => 0,
                'has_app' => 0,
                'has_groups' => 0,
                'group_values' => NULL,
                'group_default' => NULL,
                'is_sortable' => 0,
                'sort_field' => 'id',
                'sort_order' => 'asc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 1,
            ),
            9 => 
            array (
                'id' => 23,
                'entity_id' => 34,
                'has_user' => 0,
                'has_lang' => 0,
                'has_slug' => 0,
                'has_lead' => 0,
                'has_body' => 0,
                'has_status' => 0,
                'has_hideinlist' => 0,
                'has_expiration' => 0,
                'has_app' => 0,
                'has_groups' => 0,
                'group_values' => NULL,
                'group_default' => NULL,
                'is_sortable' => 0,
                'sort_field' => 'created_at',
                'sort_order' => 'desc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 1,
            ),
            10 => 
            array (
                'id' => 29,
                'entity_id' => 41,
                'has_user' => 1,
                'has_lang' => 1,
                'has_slug' => 1,
                'has_lead' => 1,
                'has_body' => 1,
                'has_status' => 1,
                'has_hideinlist' => 1,
                'has_expiration' => 0,
                'has_app' => 1,
                'has_groups' => 0,
                'group_values' => NULL,
                'group_default' => NULL,
                'is_sortable' => 0,
                'sort_field' => 'id',
                'sort_order' => 'asc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 1,
            ),
            11 => 
            array (
                'id' => 30,
                'entity_id' => 42,
                'has_user' => 1,
                'has_lang' => 1,
                'has_slug' => 1,
                'has_lead' => 0,
                'has_body' => 0,
                'has_status' => 1,
                'has_hideinlist' => 1,
                'has_expiration' => 0,
                'has_app' => 0,
                'has_groups' => 0,
                'group_values' => NULL,
                'group_default' => NULL,
                'is_sortable' => 0,
                'sort_field' => 'id',
                'sort_order' => 'asc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 1,
            ),
            12 => 
            array (
                'id' => 31,
                'entity_id' => 43,
                'has_user' => 1,
                'has_lang' => 1,
                'has_slug' => 1,
                'has_lead' => 0,
                'has_body' => 0,
                'has_status' => 1,
                'has_hideinlist' => 1,
                'has_expiration' => 0,
                'has_app' => 0,
                'has_groups' => 0,
                'group_values' => NULL,
                'group_default' => NULL,
                'is_sortable' => 0,
                'sort_field' => 'id',
                'sort_order' => 'asc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 1,
            ),
            13 => 
            array (
                'id' => 32,
                'entity_id' => 44,
                'has_user' => 1,
                'has_lang' => 1,
                'has_slug' => 1,
                'has_lead' => 1,
                'has_body' => 0,
                'has_status' => 1,
                'has_hideinlist' => 1,
                'has_expiration' => 0,
                'has_app' => 0,
                'has_groups' => 0,
                'group_values' => NULL,
                'group_default' => NULL,
                'is_sortable' => 0,
                'sort_field' => 'id',
                'sort_order' => 'asc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 1,
            ),
            14 => 
            array (
                'id' => 42,
                'entity_id' => 55,
                'has_user' => 1,
                'has_lang' => 1,
                'has_slug' => 1,
                'has_lead' => 0,
                'has_body' => 0,
                'has_status' => 1,
                'has_hideinlist' => 0,
                'has_expiration' => 0,
                'has_app' => 0,
                'has_groups' => 0,
                'group_values' => '',
                'group_default' => '',
                'is_sortable' => 0,
                'sort_field' => 'id',
                'sort_order' => 'asc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 0,
            ),
            15 => 
            array (
                'id' => 43,
                'entity_id' => 56,
                'has_user' => 0,
                'has_lang' => 0,
                'has_slug' => 1,
                'has_lead' => 0,
                'has_body' => 0,
                'has_status' => 0,
                'has_hideinlist' => 0,
                'has_expiration' => 0,
                'has_app' => 0,
                'has_groups' => 0,
                'group_values' => NULL,
                'group_default' => NULL,
                'is_sortable' => 0,
                'sort_field' => 'id',
                'sort_order' => 'asc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 0,
            ),
            16 => 
            array (
                'id' => 44,
                'entity_id' => 57,
                'has_user' => 0,
                'has_lang' => 1,
                'has_slug' => 0,
                'has_lead' => 0,
                'has_body' => 0,
                'has_status' => 0,
                'has_hideinlist' => 0,
                'has_expiration' => 0,
                'has_app' => 0,
                'has_groups' => 0,
                'group_values' => '',
                'group_default' => '',
                'is_sortable' => 0,
                'sort_field' => 'id',
                'sort_order' => 'asc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 0,
            ),
            17 => 
            array (
                'id' => 45,
                'entity_id' => 58,
                'has_user' => 0,
                'has_lang' => 0,
                'has_slug' => 0,
                'has_lead' => 0,
                'has_body' => 0,
                'has_status' => 0,
                'has_hideinlist' => 0,
                'has_expiration' => 0,
                'has_app' => 0,
                'has_groups' => 1,
                'group_values' => 'company, opengraph, general, system',
                'group_default' => 'company',
                'is_sortable' => 0,
                'sort_field' => 'id',
                'sort_order' => 'asc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 0,
            ),
            18 => 
            array (
                'id' => 47,
                'entity_id' => 60,
                'has_user' => 0,
                'has_lang' => 0,
                'has_slug' => 0,
                'has_lead' => 0,
                'has_body' => 0,
                'has_status' => 0,
                'has_hideinlist' => 0,
                'has_expiration' => 0,
                'has_app' => 0,
                'has_groups' => 0,
                'group_values' => '',
                'group_default' => '',
                'is_sortable' => 0,
                'sort_field' => 'id',
                'sort_order' => 'asc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 0,
            ),
            19 => 
            array (
                'id' => 48,
                'entity_id' => 61,
                'has_user' => 0,
                'has_lang' => 1,
                'has_slug' => 0,
                'has_lead' => 0,
                'has_body' => 0,
                'has_status' => 0,
                'has_hideinlist' => 0,
                'has_expiration' => 0,
                'has_app' => 0,
                'has_groups' => 0,
                'group_values' => '',
                'group_default' => '',
                'is_sortable' => 0,
                'sort_field' => 'id',
                'sort_order' => 'asc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 0,
            ),
            20 => 
            array (
                'id' => 49,
                'entity_id' => 62,
                'has_user' => 0,
                'has_lang' => 0,
                'has_slug' => 0,
                'has_lead' => 0,
                'has_body' => 0,
                'has_status' => 1,
                'has_hideinlist' => 0,
                'has_expiration' => 0,
                'has_app' => 0,
                'has_groups' => 0,
                'group_values' => '',
                'group_default' => '',
                'is_sortable' => 0,
                'sort_field' => 'id',
                'sort_order' => 'asc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 0,
            ),
            21 => 
            array (
                'id' => 50,
                'entity_id' => 63,
                'has_user' => 0,
                'has_lang' => 0,
                'has_slug' => 0,
                'has_lead' => 0,
                'has_body' => 0,
                'has_status' => 0,
                'has_hideinlist' => 0,
                'has_expiration' => 0,
                'has_app' => 0,
                'has_groups' => 0,
                'group_values' => '',
                'group_default' => '',
                'is_sortable' => 0,
                'sort_field' => 'id',
                'sort_order' => 'asc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 0,
            ),
            22 => 
            array (
                'id' => 51,
                'entity_id' => 64,
                'has_user' => 0,
                'has_lang' => 0,
                'has_slug' => 0,
                'has_lead' => 0,
                'has_body' => 0,
                'has_status' => 0,
                'has_hideinlist' => 0,
                'has_expiration' => 0,
                'has_app' => 0,
                'has_groups' => 0,
                'group_values' => '',
                'group_default' => '',
                'is_sortable' => 0,
                'sort_field' => 'id',
                'sort_order' => 'asc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 0,
            ),
            23 => 
            array (
                'id' => 52,
                'entity_id' => 65,
                'has_user' => 0,
                'has_lang' => 0,
                'has_slug' => 0,
                'has_lead' => 0,
                'has_body' => 0,
                'has_status' => 0,
                'has_hideinlist' => 0,
                'has_expiration' => 0,
                'has_app' => 0,
                'has_groups' => 0,
                'group_values' => NULL,
                'group_default' => NULL,
                'is_sortable' => 1,
                'sort_field' => 'position',
                'sort_order' => 'asc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 0,
            ),
            24 => 
            array (
                'id' => 53,
                'entity_id' => 66,
                'has_user' => 0,
                'has_lang' => 1,
                'has_slug' => 1,
                'has_lead' => 0,
                'has_body' => 1,
                'has_status' => 1,
                'has_hideinlist' => 0,
                'has_expiration' => 0,
                'has_app' => 0,
                'has_groups' => 0,
                'group_values' => NULL,
                'group_default' => NULL,
                'is_sortable' => 0,
                'sort_field' => 'id',
                'sort_order' => 'asc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 0,
            ),
            25 => 
            array (
                'id' => 54,
                'entity_id' => 67,
                'has_user' => 0,
                'has_lang' => 1,
                'has_slug' => 0,
                'has_lead' => 0,
                'has_body' => 0,
                'has_status' => 0,
                'has_hideinlist' => 0,
                'has_expiration' => 0,
                'has_app' => 0,
                'has_groups' => 0,
                'group_values' => '',
                'group_default' => '',
                'is_sortable' => 0,
                'sort_field' => 'id',
                'sort_order' => 'asc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 0,
            ),
            26 => 
            array (
                'id' => 55,
                'entity_id' => 68,
                'has_user' => 1,
                'has_lang' => 1,
                'has_slug' => 1,
                'has_lead' => 0,
                'has_body' => 1,
                'has_status' => 1,
                'has_hideinlist' => 1,
                'has_expiration' => 0,
                'has_app' => 0,
                'has_groups' => 0,
                'group_values' => NULL,
                'group_default' => NULL,
                'is_sortable' => 1,
                'sort_field' => 'position',
                'sort_order' => 'asc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 1,
            ),
            27 => 
            array (
                'id' => 56,
                'entity_id' => 69,
                'has_user' => 0,
                'has_lang' => 0,
                'has_slug' => 1,
                'has_lead' => 0,
                'has_body' => 0,
                'has_status' => 0,
                'has_hideinlist' => 0,
                'has_expiration' => 0,
                'has_app' => 0,
                'has_groups' => 0,
                'group_values' => NULL,
                'group_default' => NULL,
                'is_sortable' => 0,
                'sort_field' => 'created_at',
                'sort_order' => 'desc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 1,
            ),
            28 => 
            array (
                'id' => 57,
                'entity_id' => 70,
                'has_user' => 1,
                'has_lang' => 1,
                'has_slug' => 1,
                'has_lead' => 1,
                'has_body' => 1,
                'has_status' => 1,
                'has_hideinlist' => 1,
                'has_expiration' => 0,
                'has_app' => 0,
                'has_groups' => 0,
                'group_values' => NULL,
                'group_default' => NULL,
                'is_sortable' => 1,
                'sort_field' => 'position',
                'sort_order' => 'asc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 1,
            ),
            29 => 
            array (
                'id' => 58,
                'entity_id' => 71,
                'has_user' => 1,
                'has_lang' => 1,
                'has_slug' => 1,
                'has_lead' => 1,
                'has_body' => 0,
                'has_status' => 1,
                'has_hideinlist' => 1,
                'has_expiration' => 0,
                'has_app' => 0,
                'has_groups' => 0,
                'group_values' => NULL,
                'group_default' => NULL,
                'is_sortable' => 1,
                'sort_field' => 'position',
                'sort_order' => 'asc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 1,
            ),
            30 => 
            array (
                'id' => 72,
                'entity_id' => 85,
                'has_user' => 1,
                'has_lang' => 1,
                'has_slug' => 1,
                'has_lead' => 1,
                'has_body' => 1,
                'has_status' => 1,
                'has_hideinlist' => 1,
                'has_expiration' => 1,
                'has_app' => 1,
                'has_groups' => 0,
                'group_values' => NULL,
                'group_default' => NULL,
                'is_sortable' => 1,
                'sort_field' => 'position',
                'sort_order' => 'asc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 1,
            ),
            31 => 
            array (
                'id' => 73,
                'entity_id' => 86,
                'has_user' => 1,
                'has_lang' => 1,
                'has_slug' => 1,
                'has_lead' => 1,
                'has_body' => 1,
                'has_status' => 1,
                'has_hideinlist' => 0,
                'has_expiration' => 0,
                'has_app' => 0,
                'has_groups' => 0,
                'group_values' => NULL,
                'group_default' => NULL,
                'is_sortable' => 0,
                'sort_field' => 'id',
                'sort_order' => 'asc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 1,
            ),
            32 => 
            array (
                'id' => 75,
                'entity_id' => 89,
                'has_user' => 0,
                'has_lang' => 0,
                'has_slug' => 0,
                'has_lead' => 0,
                'has_body' => 0,
                'has_status' => 0,
                'has_hideinlist' => 0,
                'has_expiration' => 0,
                'has_app' => 0,
                'has_groups' => 1,
                'group_values' => 'module, larawidget, textwidget, entitywidget, sliderwidget, ctawidget, pagetitlewidget',
                'group_default' => NULL,
                'is_sortable' => 0,
                'sort_field' => NULL,
                'sort_order' => 'asc',
                'sort2_field' => NULL,
                'sort2_order' => NULL,
                'has_fields' => 0,
            ),
        ));
        
        
    }
}