<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class LaraFormClassicformsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('lara_form_classicforms')->delete();
        
        \DB::table('lara_form_classicforms')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => 'Sybrand Hoeksma',
                'mydate' => NULL,
                'myboolean' => 0,
                'myyesno' => 0,
                'myradio' => NULL,
                'myselect' => NULL,
                'mycomment' => NULL,
                'myemail' => NULL,
                'myname' => NULL,
                'slug' => NULL,
                'slug_lock' => 0,
                'created_at' => '2019-12-17 10:01:41',
                'updated_at' => '2019-12-17 10:01:41',
                'deleted_at' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
                'ipaddress' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'title' => 'Sybrand Hoeksma',
                'mydate' => NULL,
                'myboolean' => 0,
                'myyesno' => 0,
                'myradio' => NULL,
                'myselect' => NULL,
                'mycomment' => NULL,
                'myemail' => NULL,
                'myname' => NULL,
                'slug' => NULL,
                'slug_lock' => 0,
                'created_at' => '2019-12-17 10:03:06',
                'updated_at' => '2019-12-17 10:03:06',
                'deleted_at' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
                'ipaddress' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'Sybrand Hoeksma',
                'mydate' => NULL,
                'myboolean' => 0,
                'myyesno' => 0,
                'myradio' => NULL,
                'myselect' => NULL,
                'mycomment' => NULL,
                'myemail' => NULL,
                'myname' => NULL,
                'slug' => NULL,
                'slug_lock' => 0,
                'created_at' => '2019-12-17 10:04:30',
                'updated_at' => '2019-12-17 10:04:30',
                'deleted_at' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
                'ipaddress' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'title' => 'Sybrand Hoeksma',
                'mydate' => NULL,
                'myboolean' => 0,
                'myyesno' => 0,
                'myradio' => NULL,
                'myselect' => NULL,
                'mycomment' => NULL,
                'myemail' => NULL,
                'myname' => NULL,
                'slug' => NULL,
                'slug_lock' => 0,
                'created_at' => '2019-12-17 10:07:37',
                'updated_at' => '2019-12-17 10:07:37',
                'deleted_at' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
                'ipaddress' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'title' => 'Sybrand Hoeksma',
                'mydate' => NULL,
                'myboolean' => 0,
                'myyesno' => 0,
                'myradio' => NULL,
                'myselect' => NULL,
                'mycomment' => NULL,
                'myemail' => NULL,
                'myname' => NULL,
                'slug' => NULL,
                'slug_lock' => 0,
                'created_at' => '2019-12-17 10:07:40',
                'updated_at' => '2019-12-17 10:07:40',
                'deleted_at' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
                'ipaddress' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'title' => 'Sybrand Hoeksma',
                'mydate' => NULL,
                'myboolean' => 0,
                'myyesno' => 0,
                'myradio' => NULL,
                'myselect' => NULL,
                'mycomment' => NULL,
                'myemail' => NULL,
                'myname' => NULL,
                'slug' => NULL,
                'slug_lock' => 0,
                'created_at' => '2019-12-17 10:08:18',
                'updated_at' => '2019-12-17 10:08:18',
                'deleted_at' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
                'ipaddress' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'title' => 'Sybrand Hoeksma',
                'mydate' => NULL,
                'myboolean' => 0,
                'myyesno' => 0,
                'myradio' => NULL,
                'myselect' => NULL,
                'mycomment' => NULL,
                'myemail' => NULL,
                'myname' => NULL,
                'slug' => NULL,
                'slug_lock' => 0,
                'created_at' => '2019-12-17 10:08:22',
                'updated_at' => '2019-12-17 10:08:22',
                'deleted_at' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
                'ipaddress' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'title' => 'Sybrand Hoeksma',
                'mydate' => NULL,
                'myboolean' => 0,
                'myyesno' => 0,
                'myradio' => NULL,
                'myselect' => NULL,
                'mycomment' => NULL,
                'myemail' => NULL,
                'myname' => NULL,
                'slug' => NULL,
                'slug_lock' => 0,
                'created_at' => '2019-12-17 10:08:29',
                'updated_at' => '2019-12-17 10:08:29',
                'deleted_at' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
                'ipaddress' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'title' => 'Sybrand Hoeksma',
                'mydate' => NULL,
                'myboolean' => 0,
                'myyesno' => 0,
                'myradio' => NULL,
                'myselect' => NULL,
                'mycomment' => NULL,
                'myemail' => NULL,
                'myname' => NULL,
                'slug' => NULL,
                'slug_lock' => 0,
                'created_at' => '2019-12-17 10:09:19',
                'updated_at' => '2019-12-17 10:09:19',
                'deleted_at' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
                'ipaddress' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'title' => 'Sybrand Hoeksma',
                'mydate' => NULL,
                'myboolean' => 0,
                'myyesno' => 0,
                'myradio' => NULL,
                'myselect' => NULL,
                'mycomment' => NULL,
                'myemail' => NULL,
                'myname' => NULL,
                'slug' => NULL,
                'slug_lock' => 0,
                'created_at' => '2019-12-17 10:46:50',
                'updated_at' => '2019-12-17 10:46:50',
                'deleted_at' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
                'ipaddress' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'title' => 'SH',
                'mydate' => NULL,
                'myboolean' => 0,
                'myyesno' => 0,
                'myradio' => NULL,
                'myselect' => NULL,
                'mycomment' => NULL,
                'myemail' => NULL,
                'myname' => NULL,
                'slug' => NULL,
                'slug_lock' => 0,
                'created_at' => '2019-12-17 10:47:16',
                'updated_at' => '2019-12-17 10:47:16',
                'deleted_at' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
                'ipaddress' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'title' => 'Sybrand Hoeksma',
                'mydate' => NULL,
                'myboolean' => 0,
                'myyesno' => 0,
                'myradio' => NULL,
                'myselect' => NULL,
                'mycomment' => NULL,
                'myemail' => NULL,
                'myname' => NULL,
                'slug' => 'sybrand-hoeksma',
                'slug_lock' => 0,
                'created_at' => '2023-03-19 20:42:25',
                'updated_at' => '2023-03-19 20:42:25',
                'deleted_at' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
                'ipaddress' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'title' => 'Sybrand Hoeksma',
                'mydate' => NULL,
                'myboolean' => 0,
                'myyesno' => 0,
                'myradio' => NULL,
                'myselect' => NULL,
                'mycomment' => NULL,
                'myemail' => NULL,
                'myname' => NULL,
                'slug' => 'sybrand-hoeksma-1',
                'slug_lock' => 0,
                'created_at' => '2023-03-19 20:42:59',
                'updated_at' => '2023-03-19 20:42:59',
                'deleted_at' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
                'ipaddress' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'title' => 'Sybrand Hoeksma',
                'mydate' => NULL,
                'myboolean' => 0,
                'myyesno' => 0,
                'myradio' => NULL,
                'myselect' => NULL,
                'mycomment' => NULL,
                'myemail' => NULL,
                'myname' => NULL,
                'slug' => 'sybrand-hoeksma-2',
                'slug_lock' => 0,
                'created_at' => '2023-03-19 20:47:43',
                'updated_at' => '2023-03-19 20:47:43',
                'deleted_at' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
                'ipaddress' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'title' => 'Sybrand Hoeksma',
                'mydate' => NULL,
                'myboolean' => 0,
                'myyesno' => 0,
                'myradio' => NULL,
                'myselect' => NULL,
                'mycomment' => NULL,
                'myemail' => NULL,
                'myname' => NULL,
                'slug' => 'sybrand-hoeksma-3',
                'slug_lock' => 0,
                'created_at' => '2023-03-19 20:48:32',
                'updated_at' => '2023-03-19 20:48:32',
                'deleted_at' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
                'ipaddress' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'title' => 'Sybrand Hoeksma',
                'mydate' => NULL,
                'myboolean' => 0,
                'myyesno' => 0,
                'myradio' => NULL,
                'myselect' => NULL,
                'mycomment' => NULL,
                'myemail' => NULL,
                'myname' => NULL,
                'slug' => 'sybrand-hoeksma-4',
                'slug_lock' => 0,
                'created_at' => '2023-03-19 20:49:05',
                'updated_at' => '2023-03-19 20:49:05',
                'deleted_at' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
                'ipaddress' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'title' => 'Sybrand Hoeksma',
                'mydate' => NULL,
                'myboolean' => 0,
                'myyesno' => 0,
                'myradio' => NULL,
                'myselect' => NULL,
                'mycomment' => NULL,
                'myemail' => NULL,
                'myname' => NULL,
                'slug' => 'sybrand-hoeksma-5',
                'slug_lock' => 0,
                'created_at' => '2023-03-19 20:51:51',
                'updated_at' => '2023-03-19 20:51:51',
                'deleted_at' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
                'ipaddress' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'title' => 'Sybrand Hoeksma',
                'mydate' => NULL,
                'myboolean' => 0,
                'myyesno' => 0,
                'myradio' => NULL,
                'myselect' => NULL,
                'mycomment' => NULL,
                'myemail' => NULL,
                'myname' => NULL,
                'slug' => 'sybrand-hoeksma-6',
                'slug_lock' => 0,
                'created_at' => '2023-03-19 20:54:07',
                'updated_at' => '2023-03-19 20:54:07',
                'deleted_at' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
                'ipaddress' => NULL,
            ),
        ));
        
        
    }
}