<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class LaraEntEntitiesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('lara_ent_entities')->delete();
        
        \DB::table('lara_ent_entities')->insert(array (
            0 => 
            array (
                'id' => 1,
                'group_id' => 1,
                'title' => 'Pages',
                'entity_model_class' => 'Lara\\Common\\Models\\Page',
                'entity_key' => 'page',
                'entity_controller' => 'PagesController',
                'resource_routes' => 1,
                'has_front_auth' => 0,
                'menu_parent' => 'root',
                'menu_position' => 103,
                'menu_icon' => 'fad fa-file-alt',
                'created_at' => NULL,
                'updated_at' => '2023-05-24 16:03:10',
                'locked_at' => '2023-05-24 16:03:10',
                'locked_by' => 2,
            ),
            1 => 
            array (
                'id' => 2,
                'group_id' => 9,
                'title' => 'News',
                'entity_model_class' => 'Eve\\Models\\Blog',
                'entity_key' => 'blog',
                'entity_controller' => 'BlogsController',
                'resource_routes' => 1,
                'has_front_auth' => 0,
                'menu_parent' => 'modules',
                'menu_position' => 200,
                'menu_icon' => 'fad fa-file-alt',
                'created_at' => NULL,
                'updated_at' => '2023-10-14 12:25:27',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'group_id' => 9,
                'title' => 'Team',
                'entity_model_class' => 'Eve\\Models\\Team',
                'entity_key' => 'team',
                'entity_controller' => 'TeamsController',
                'resource_routes' => 1,
                'has_front_auth' => 0,
                'menu_parent' => 'modules',
                'menu_position' => 201,
                'menu_icon' => NULL,
                'created_at' => NULL,
                'updated_at' => '2023-09-22 15:14:08',
                'locked_at' => '2023-09-22 15:14:08',
                'locked_by' => 2,
            ),
            3 => 
            array (
                'id' => 17,
                'group_id' => 9,
                'title' => 'Events',
                'entity_model_class' => 'Eve\\Models\\Event',
                'entity_key' => 'event',
                'entity_controller' => 'EventsController',
                'resource_routes' => 1,
                'has_front_auth' => 0,
                'menu_parent' => 'modules',
                'menu_position' => 202,
                'menu_icon' => NULL,
                'created_at' => '2017-09-30 12:08:10',
                'updated_at' => '2023-09-21 14:21:56',
                'locked_at' => '2023-09-21 14:21:56',
                'locked_by' => 2,
            ),
            4 => 
            array (
                'id' => 18,
                'group_id' => 9,
                'title' => 'Locations',
                'entity_model_class' => 'Eve\\Models\\Location',
                'entity_key' => 'location',
                'entity_controller' => 'LocationsController',
                'resource_routes' => 1,
                'has_front_auth' => 0,
                'menu_parent' => 'modules',
                'menu_position' => 203,
                'menu_icon' => NULL,
                'created_at' => '2017-09-30 12:08:41',
                'updated_at' => '2023-10-17 15:36:49',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            5 => 
            array (
                'id' => 20,
                'group_id' => 2,
                'title' => 'Sliders',
                'entity_model_class' => 'Lara\\Common\\Models\\Slider',
                'entity_key' => 'slider',
                'entity_controller' => 'SlidersController',
                'resource_routes' => 1,
                'has_front_auth' => 0,
                'menu_parent' => 'blocks',
                'menu_position' => 301,
                'menu_icon' => NULL,
                'created_at' => '2017-10-08 13:24:29',
                'updated_at' => '2024-01-03 12:19:56',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            6 => 
            array (
                'id' => 27,
                'group_id' => 2,
                'title' => 'Widgets',
                'entity_model_class' => 'Lara\\Common\\Models\\Larawidget',
                'entity_key' => 'larawidget',
                'entity_controller' => 'LarawidgetsController',
                'resource_routes' => 1,
                'has_front_auth' => 0,
                'menu_parent' => 'blocks',
                'menu_position' => 302,
                'menu_icon' => NULL,
                'created_at' => '2017-12-07 16:07:16',
                'updated_at' => '2021-01-25 12:37:16',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            7 => 
            array (
                'id' => 29,
                'group_id' => 9,
                'title' => 'Portfolio',
                'entity_model_class' => 'Eve\\Models\\Portfolio',
                'entity_key' => 'portfolio',
                'entity_controller' => 'PortfoliosController',
                'resource_routes' => 1,
                'has_front_auth' => 0,
                'menu_parent' => 'modules',
                'menu_position' => 205,
                'menu_icon' => NULL,
                'created_at' => '2017-12-08 15:40:52',
                'updated_at' => '2023-03-11 13:17:27',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            8 => 
            array (
                'id' => 31,
                'group_id' => 2,
                'title' => 'Call-to-action',
                'entity_model_class' => 'Lara\\Common\\Models\\Cta',
                'entity_key' => 'cta',
                'entity_controller' => 'CtasController',
                'resource_routes' => 1,
                'has_front_auth' => 0,
                'menu_parent' => 'blocks',
                'menu_position' => 303,
                'menu_icon' => NULL,
                'created_at' => '2017-12-23 11:41:56',
                'updated_at' => '2023-09-20 13:21:17',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            9 => 
            array (
                'id' => 34,
                'group_id' => 8,
                'title' => 'Contactform',
                'entity_model_class' => 'Eve\\Models\\Contactform',
                'entity_key' => 'contactform',
                'entity_controller' => 'ContactformsController',
                'resource_routes' => 1,
                'has_front_auth' => 0,
                'menu_parent' => 'forms',
                'menu_position' => 310,
                'menu_icon' => NULL,
                'created_at' => '2018-01-15 21:07:17',
                'updated_at' => '2023-11-10 10:23:06',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            10 => 
            array (
                'id' => 41,
                'group_id' => 9,
                'title' => 'Products',
                'entity_model_class' => 'Eve\\Models\\Product',
                'entity_key' => 'product',
                'entity_controller' => 'ProductsController',
                'resource_routes' => 1,
                'has_front_auth' => 0,
                'menu_parent' => 'modules',
                'menu_position' => NULL,
                'menu_icon' => NULL,
                'created_at' => '2018-02-21 09:33:29',
                'updated_at' => '2023-11-10 10:11:27',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            11 => 
            array (
                'id' => 42,
                'group_id' => 9,
                'title' => 'Galleries',
                'entity_model_class' => 'Eve\\Models\\Gallery',
                'entity_key' => 'gallery',
                'entity_controller' => 'GalleriesController',
                'resource_routes' => 1,
                'has_front_auth' => 0,
                'menu_parent' => 'modules',
                'menu_position' => 280,
                'menu_icon' => NULL,
                'created_at' => '2018-04-20 08:45:01',
                'updated_at' => '2023-04-14 16:05:26',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            12 => 
            array (
                'id' => 43,
                'group_id' => 9,
                'title' => 'Videos',
                'entity_model_class' => 'Eve\\Models\\Video',
                'entity_key' => 'video',
                'entity_controller' => 'VideosController',
                'resource_routes' => 1,
                'has_front_auth' => 0,
                'menu_parent' => 'modules',
                'menu_position' => 290,
                'menu_icon' => NULL,
                'created_at' => '2018-04-20 08:50:50',
                'updated_at' => '2023-10-11 11:08:59',
                'locked_at' => '2023-10-11 11:08:59',
                'locked_by' => 2,
            ),
            13 => 
            array (
                'id' => 44,
                'group_id' => 9,
                'title' => 'Docs',
                'entity_model_class' => 'Eve\\Models\\Doc',
                'entity_key' => 'doc',
                'entity_controller' => 'DocsController',
                'resource_routes' => 1,
                'has_front_auth' => 0,
                'menu_parent' => 'modules',
                'menu_position' => 240,
                'menu_icon' => NULL,
                'created_at' => '2018-04-20 08:56:49',
                'updated_at' => '2023-06-22 15:14:25',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            14 => 
            array (
                'id' => 55,
                'group_id' => 3,
                'title' => 'Menu',
                'entity_model_class' => 'Lara\\Common\\Models\\Menuitem',
                'entity_key' => 'menuitem',
                'entity_controller' => 'MenuitemsController',
                'resource_routes' => 1,
                'has_front_auth' => 0,
                'menu_parent' => 'menu',
                'menu_position' => 151,
                'menu_icon' => NULL,
                'created_at' => '2019-07-14 15:19:59',
                'updated_at' => '2023-03-02 14:05:03',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            15 => 
            array (
                'id' => 56,
                'group_id' => 3,
                'title' => 'Menus',
                'entity_model_class' => 'Lara\\Common\\Models\\Menu',
                'entity_key' => 'menu',
                'entity_controller' => 'MenusController',
                'resource_routes' => 1,
                'has_front_auth' => 0,
                'menu_parent' => 'menu',
                'menu_position' => NULL,
                'menu_icon' => NULL,
                'created_at' => '2019-07-14 18:00:38',
                'updated_at' => '2020-12-28 19:45:34',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            16 => 
            array (
                'id' => 57,
                'group_id' => 7,
                'title' => 'Translations',
                'entity_model_class' => 'Lara\\Common\\Models\\Translation',
                'entity_key' => 'translation',
                'entity_controller' => 'TranslationsController',
                'resource_routes' => 1,
                'has_front_auth' => 0,
                'menu_parent' => 'tools',
                'menu_position' => 804,
                'menu_icon' => NULL,
                'created_at' => '2019-07-16 19:17:57',
                'updated_at' => '2019-07-17 12:32:51',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            17 => 
            array (
                'id' => 58,
                'group_id' => 7,
                'title' => 'Settings',
                'entity_model_class' => 'Lara\\Common\\Models\\Setting',
                'entity_key' => 'setting',
                'entity_controller' => 'SettingsController',
                'resource_routes' => 1,
                'has_front_auth' => 0,
                'menu_parent' => 'tools',
                'menu_position' => 803,
                'menu_icon' => NULL,
                'created_at' => '2019-07-16 19:24:54',
                'updated_at' => '2019-12-18 12:22:46',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            18 => 
            array (
                'id' => 60,
                'group_id' => 5,
                'title' => 'Users',
                'entity_model_class' => 'Lara\\Common\\Models\\User',
                'entity_key' => 'user',
                'entity_controller' => 'UsersController',
                'resource_routes' => 1,
                'has_front_auth' => 0,
                'menu_parent' => 'users',
                'menu_position' => 901,
                'menu_icon' => NULL,
                'created_at' => '2019-07-16 19:32:24',
                'updated_at' => '2019-07-16 20:19:11',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            19 => 
            array (
                'id' => 61,
                'group_id' => 3,
                'title' => 'Seos',
                'entity_model_class' => 'Lara\\Common\\Models\\Seo',
                'entity_key' => 'seo',
                'entity_controller' => 'SeosController',
                'resource_routes' => 1,
                'has_front_auth' => 0,
                'menu_parent' => 'menu',
                'menu_position' => 153,
                'menu_icon' => NULL,
                'created_at' => '2019-07-16 20:11:45',
                'updated_at' => '2019-07-16 20:13:03',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            20 => 
            array (
                'id' => 62,
                'group_id' => 3,
                'title' => 'Redirects',
                'entity_model_class' => 'Lara\\Common\\Models\\Redirect',
                'entity_key' => 'redirect',
                'entity_controller' => 'RedirectsController',
                'resource_routes' => 1,
                'has_front_auth' => 0,
                'menu_parent' => 'menu',
                'menu_position' => 155,
                'menu_icon' => NULL,
                'created_at' => '2019-07-16 20:24:03',
                'updated_at' => '2020-08-04 12:18:29',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            21 => 
            array (
                'id' => 63,
                'group_id' => 5,
                'title' => 'Roles',
                'entity_model_class' => 'Lara\\Common\\Models\\Userrole',
                'entity_key' => 'role',
                'entity_controller' => 'RolesController',
                'resource_routes' => 1,
                'has_front_auth' => 0,
                'menu_parent' => 'users',
                'menu_position' => 902,
                'menu_icon' => NULL,
                'created_at' => '2019-07-16 20:32:35',
                'updated_at' => '2019-07-16 20:40:06',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            22 => 
            array (
                'id' => 64,
                'group_id' => 5,
                'title' => 'Abilities',
                'entity_model_class' => 'Lara\\Common\\Models\\Userability',
                'entity_key' => 'ability',
                'entity_controller' => 'AbilitiesController',
                'resource_routes' => 1,
                'has_front_auth' => 0,
                'menu_parent' => 'users',
                'menu_position' => 903,
                'menu_icon' => NULL,
                'created_at' => '2019-07-16 20:40:29',
                'updated_at' => '2019-07-16 20:41:31',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            23 => 
            array (
                'id' => 65,
                'group_id' => 6,
                'title' => 'Entitygroups',
                'entity_model_class' => 'Lara\\Common\\Models\\Entitygroup',
                'entity_key' => 'entitygroup',
                'entity_controller' => 'EntitygroupsController',
                'resource_routes' => 0,
                'has_front_auth' => 0,
                'menu_parent' => NULL,
                'menu_position' => NULL,
                'menu_icon' => NULL,
                'created_at' => '2019-07-17 12:56:30',
                'updated_at' => '2019-07-17 12:56:30',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            24 => 
            array (
                'id' => 66,
                'group_id' => 4,
                'title' => 'Tags',
                'entity_model_class' => 'Lara\\Common\\Models\\Tag',
                'entity_key' => 'tag',
                'entity_controller' => 'TagsController',
                'resource_routes' => 1,
                'has_front_auth' => 0,
                'menu_parent' => NULL,
                'menu_position' => NULL,
                'menu_icon' => NULL,
                'created_at' => '2019-07-17 13:24:21',
                'updated_at' => '2020-04-20 16:18:32',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            25 => 
            array (
                'id' => 67,
                'group_id' => 3,
                'title' => 'Languages',
                'entity_model_class' => 'Lara\\Common\\Models\\Language',
                'entity_key' => 'language',
                'entity_controller' => 'LanguagesController',
                'resource_routes' => 1,
                'has_front_auth' => 0,
                'menu_parent' => 'menu',
                'menu_position' => 154,
                'menu_icon' => NULL,
                'created_at' => '2019-07-17 18:21:20',
                'updated_at' => '2019-07-17 18:21:42',
                'locked_at' => '2019-07-17 18:21:42',
                'locked_by' => 2,
            ),
            26 => 
            array (
                'id' => 68,
                'group_id' => 9,
                'title' => 'Sponsors',
                'entity_model_class' => 'Eve\\Models\\Sponsor',
                'entity_key' => 'sponsor',
                'entity_controller' => 'SponsorsController',
                'resource_routes' => 1,
                'has_front_auth' => 0,
                'menu_parent' => 'modules',
                'menu_position' => NULL,
                'menu_icon' => NULL,
                'created_at' => '2019-08-12 16:08:11',
                'updated_at' => '2023-11-10 10:11:20',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            27 => 
            array (
                'id' => 69,
                'group_id' => 8,
                'title' => 'Classicforms',
                'entity_model_class' => 'Eve\\Models\\Classicform',
                'entity_key' => 'classicform',
                'entity_controller' => 'ClassicformsController',
                'resource_routes' => 1,
                'has_front_auth' => 0,
                'menu_parent' => 'forms',
                'menu_position' => NULL,
                'menu_icon' => NULL,
                'created_at' => '2019-12-17 09:27:49',
                'updated_at' => '2023-05-11 12:00:32',
                'locked_at' => '2023-05-11 12:00:32',
                'locked_by' => 2,
            ),
            28 => 
            array (
                'id' => 70,
                'group_id' => 9,
                'title' => 'Stories',
                'entity_model_class' => 'Eve\\Models\\Story',
                'entity_key' => 'story',
                'entity_controller' => 'StoriesController',
                'resource_routes' => 1,
                'has_front_auth' => 0,
                'menu_parent' => 'modules',
                'menu_position' => NULL,
                'menu_icon' => NULL,
                'created_at' => '2020-06-17 16:31:52',
                'updated_at' => '2020-06-17 16:36:25',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            29 => 
            array (
                'id' => 71,
                'group_id' => 9,
                'title' => 'Testimonials',
                'entity_model_class' => 'Eve\\Models\\Testimonial',
                'entity_key' => 'testimonial',
                'entity_controller' => 'TestimonialsController',
                'resource_routes' => 1,
                'has_front_auth' => 0,
                'menu_parent' => 'modules',
                'menu_position' => 208,
                'menu_icon' => NULL,
                'created_at' => '2020-06-25 09:58:26',
                'updated_at' => '2023-10-13 16:48:19',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            30 => 
            array (
                'id' => 85,
                'group_id' => 9,
                'title' => 'Cities',
                'entity_model_class' => 'Eve\\Models\\City',
                'entity_key' => 'city',
                'entity_controller' => 'CitiesController',
                'resource_routes' => 1,
                'has_front_auth' => 0,
                'menu_parent' => 'modules',
                'menu_position' => NULL,
                'menu_icon' => NULL,
                'created_at' => '2020-12-23 12:21:15',
                'updated_at' => '2023-11-10 10:11:34',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            31 => 
            array (
                'id' => 86,
                'group_id' => 9,
                'title' => 'Services',
                'entity_model_class' => 'Eve\\Models\\Service',
                'entity_key' => 'service',
                'entity_controller' => 'ServicesController',
                'resource_routes' => 1,
                'has_front_auth' => 0,
                'menu_parent' => 'modules',
                'menu_position' => 209,
                'menu_icon' => NULL,
                'created_at' => '2023-03-11 14:10:05',
                'updated_at' => '2023-07-05 16:46:49',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
        ));
        
        
    }
}