<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class LaraBlocksLarawidgetsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('lara_blocks_larawidgets')->delete();
        
        \DB::table('lara_blocks_larawidgets')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 2,
                'language_parent' => NULL,
                'language' => 'nl',
                'title' => 'Software Development',
                'customtags' => '',
                'iconalign' => '',
                'iconclass' => '',
                'linkurl' => '',
                'linktext' => '',
                'isglobal' => 0,
                'type' => 'text',
                'hook' => 'home1',
                'template' => 'swiperslide',
                'sortorder' => 0,
                'usecache' => 0,
                'maxitems' => 0,
                'imgreq' => 0,
                'term' => '',
                'relentkey' => '',
                'slug' => 'software-development',
                'slug_lock' => 0,
                'body' => '<p>Commodo senectus massa est urna mi. Mattis dis arcu aenean libero viverra gravida.</p>',
                'created_at' => '2017-12-07 16:13:20',
                'updated_at' => '2023-09-20 16:56:37',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2023-03-11 17:25:00',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 2,
                'language_parent' => NULL,
                'language' => 'nl',
                'title' => 'App Development',
                'customtags' => '',
                'iconalign' => '',
                'iconclass' => '',
                'linkurl' => '',
                'linktext' => '',
                'isglobal' => 0,
                'type' => 'text',
                'hook' => 'home2',
                'template' => 'swiperslide',
                'sortorder' => 0,
                'usecache' => 0,
                'maxitems' => 0,
                'imgreq' => 0,
                'term' => '',
                'relentkey' => '',
                'slug' => 'app-development',
                'slug_lock' => 0,
                'body' => '<p>Enim vehicula integer mattis morbi risus. Hendrerit pharetra arcu quam viverra.</p>',
                'created_at' => '2017-12-14 18:31:35',
                'updated_at' => '2023-03-11 17:37:22',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2019-08-09 00:00:00',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 2,
                'language_parent' => NULL,
                'language' => 'nl',
                'title' => 'Support & Maintenance',
                'customtags' => '',
                'iconalign' => '',
                'iconclass' => '',
                'linkurl' => '',
                'linktext' => '',
                'isglobal' => 0,
                'type' => 'text',
                'hook' => 'home3',
                'template' => 'swiperslide',
                'sortorder' => 0,
                'usecache' => 0,
                'maxitems' => 0,
                'imgreq' => 0,
                'term' => '',
                'relentkey' => '',
                'slug' => 'support-maintenance',
                'slug_lock' => 0,
                'body' => '<p>Turpis ultrices lacinia ut placerat dignissim morbi. Amet lectus sed tortor in elit adipiscing magnis.</p>',
                'created_at' => '2017-12-14 19:20:41',
                'updated_at' => '2023-03-11 17:41:15',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2019-08-09 00:00:00',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 2,
                'language_parent' => NULL,
                'language' => 'nl',
                'title' => 'Software QA & Testing',
                'customtags' => '',
                'iconalign' => '',
                'iconclass' => '',
                'linkurl' => '',
                'linktext' => '',
                'isglobal' => 0,
                'type' => 'text',
                'hook' => 'home4',
                'template' => 'swiperslide',
                'sortorder' => 0,
                'usecache' => 0,
                'maxitems' => 0,
                'imgreq' => 0,
                'term' => '',
                'relentkey' => '',
                'slug' => 'software-qa-testing',
                'slug_lock' => 0,
                'body' => '<p>Amet felis viverra proin feugiat. Eget metus metus lorem dolor pellentesque.</p>',
                'created_at' => '2017-12-15 11:47:52',
                'updated_at' => '2023-03-11 17:42:44',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2023-03-11 17:42:00',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            4 => 
            array (
                'id' => 13,
                'user_id' => 2,
                'language_parent' => NULL,
                'language' => 'nl',
                'title' => 'Lara 7',
                'customtags' => '',
                'iconalign' => '',
                'iconclass' => '',
                'linkurl' => '',
                'linktext' => '',
                'isglobal' => 1,
                'type' => 'text',
                'hook' => 'footer1',
                'template' => 'footer',
                'sortorder' => 0,
                'usecache' => 0,
                'maxitems' => 0,
                'imgreq' => 0,
                'term' => '',
                'relentkey' => '',
                'slug' => 'lara-7',
                'slug_lock' => 0,
                'body' => '<p class="fs-sm text-light opacity-80 pb-lg-16 mb-24">Proin ipsum pharetra, senectus eget scelerisque varius pretium platea velit. Lacus, eget eu vitae nullam proin turpis etiam mi sit. Non feugiat feugiat egestas nulla nec. Arcu tempus, eget elementum dolor ullamcorper sodales ultrices eros.</p>',
                'created_at' => '2018-03-04 15:11:31',
                'updated_at' => '2023-09-20 16:56:48',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2023-03-12 12:25:00',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            5 => 
            array (
                'id' => 14,
                'user_id' => 2,
                'language_parent' => NULL,
                'language' => 'nl',
                'title' => 'Useful Links',
                'customtags' => '',
                'iconalign' => '',
                'iconclass' => '',
                'linkurl' => '',
                'linktext' => '',
                'isglobal' => 1,
                'type' => 'text',
                'hook' => 'footer2',
                'template' => 'footerlinks',
                'sortorder' => 0,
                'usecache' => 0,
                'maxitems' => 0,
                'imgreq' => 0,
                'term' => '',
                'relentkey' => '',
                'slug' => 'useful-links',
                'slug_lock' => 0,
                'body' => '<div id="useful-links" class="collapse d-lg-block" data-bs-parent="#footer-links">
<ul class="nav flex-column pb-lg-4 mb-lg-16">
<li class="nav-item"><a class="nav-link d-inline-block px-0 pt-4 pb-8" href="#">Home</a></li>
<li class="nav-item"><a class="nav-link d-inline-block px-0 pt-4 pb-8" href="#">Services</a></li>
<li class="nav-item"><a class="nav-link d-inline-block px-0 pt-4 pb-8" href="#">Case Studies</a></li>
<li class="nav-item"><a class="nav-link d-inline-block px-0 pt-4 pb-8" href="#">About Us</a></li>
<li class="nav-item"><a class="nav-link d-inline-block px-0 pt-4 pb-8" href="#">News &amp; Insights</a></li>
</ul>
<ul class="nav flex-column mb-8 mb-lg-0">
<li class="nav-item"><a class="nav-link d-inline-block px-0 pt-4 pb-8" href="#">Terms &amp; Conditions</a></li>
<li class="nav-item"><a class="nav-link d-inline-block px-0 pt-4 pb-8" href="#">Privacy Policy</a></li>
</ul>
</div>',
                'created_at' => '2018-07-23 15:25:27',
                'updated_at' => '2023-09-20 17:00:57',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2023-03-12 12:48:00',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            6 => 
            array (
                'id' => 579,
                'user_id' => 2,
                'language_parent' => 1,
                'language' => 'en',
                'title' => '[EN] Mega Menu',
                'customtags' => NULL,
                'iconalign' => 'left',
                'iconclass' => 'icon-map',
                'linkurl' => '',
                'linktext' => '',
                'isglobal' => 0,
                'type' => 'icon',
                'hook' => 'home1',
                'template' => NULL,
                'sortorder' => 0,
                'usecache' => 0,
                'maxitems' => 0,
                'imgreq' => 0,
                'term' => '',
                'relentkey' => '',
                'slug' => 'en-mega-menu',
                'slug_lock' => 0,
                'body' => '<p>[EN]</p> <p>In dui magna, posuere eget, vestibulum et, tempor auctor, justo. In ac felis quis tortor malesuada pretium.</p>',
                'created_at' => '2019-07-21 14:30:12',
                'updated_at' => '2019-07-22 15:26:14',
                'deleted_at' => NULL,
                'publish' => 0,
                'publish_from' => '2019-03-10 00:00:00',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            7 => 
            array (
                'id' => 580,
                'user_id' => 2,
                'language_parent' => 2,
                'language' => 'en',
                'title' => '[EN] Responsive Design',
                'customtags' => NULL,
                'iconalign' => 'left',
                'iconclass' => 'icon-rocket',
                'linkurl' => '',
                'linktext' => '',
                'isglobal' => 0,
                'type' => 'icon',
                'hook' => 'home2',
                'template' => NULL,
                'sortorder' => 0,
                'usecache' => 0,
                'maxitems' => 0,
                'imgreq' => 0,
                'term' => '',
                'relentkey' => '',
                'slug' => 'en-responsive-design',
                'slug_lock' => 0,
                'body' => '<p>[EN]</p> <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In dui magna posuere.</p>',
                'created_at' => '2019-07-21 14:30:12',
                'updated_at' => '2019-07-21 14:30:12',
                'deleted_at' => NULL,
                'publish' => 0,
                'publish_from' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            8 => 
            array (
                'id' => 581,
                'user_id' => 2,
                'language_parent' => 3,
                'language' => 'en',
                'title' => '[EN] Reusable Elements',
                'customtags' => NULL,
                'iconalign' => 'left',
                'iconclass' => 'icon-layers',
                'linkurl' => '',
                'linktext' => '',
                'isglobal' => 0,
                'type' => 'icon',
                'hook' => 'home3',
                'template' => NULL,
                'sortorder' => 0,
                'usecache' => 0,
                'maxitems' => 0,
                'imgreq' => 0,
                'term' => '',
                'relentkey' => '',
                'slug' => 'en-reusable-elements',
                'slug_lock' => 0,
                'body' => '<p>[EN]</p> <p>In dui magna, posuere eget, vestibulum et, tempor auctor, justo. In ac felis quis tortor malesuada pretium.</p>',
                'created_at' => '2019-07-21 14:30:12',
                'updated_at' => '2019-07-21 14:30:12',
                'deleted_at' => NULL,
                'publish' => 0,
                'publish_from' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            9 => 
            array (
                'id' => 582,
                'user_id' => 2,
                'language_parent' => 4,
                'language' => 'en',
                'title' => '[EN] Awesome Parallax',
                'customtags' => NULL,
                'iconalign' => 'left',
                'iconclass' => 'icon-star',
                'linkurl' => '',
                'linktext' => '',
                'isglobal' => 0,
                'type' => 'icon',
                'hook' => 'home4',
                'template' => NULL,
                'sortorder' => 0,
                'usecache' => 0,
                'maxitems' => 0,
                'imgreq' => 0,
                'term' => '',
                'relentkey' => '',
                'slug' => 'en-awesome-parallax',
                'slug_lock' => 0,
                'body' => '<p>[EN]</p> <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In dui magna posuere.</p>',
                'created_at' => '2019-07-21 14:30:12',
                'updated_at' => '2019-07-21 14:30:12',
                'deleted_at' => NULL,
                'publish' => 0,
                'publish_from' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            10 => 
            array (
                'id' => 583,
                'user_id' => 2,
                'language_parent' => 5,
                'language' => 'en',
                'title' => '[EN] Google Web Fonts',
                'customtags' => NULL,
                'iconalign' => 'left',
                'iconclass' => 'icon-cloud-download',
                'linkurl' => '',
                'linktext' => '',
                'isglobal' => 0,
                'type' => 'icon',
                'hook' => 'home5',
                'template' => NULL,
                'sortorder' => 0,
                'usecache' => 0,
                'maxitems' => 0,
                'imgreq' => 0,
                'term' => '',
                'relentkey' => '',
                'slug' => 'en-google-web-fonts',
                'slug_lock' => 0,
                'body' => '<p>[EN]</p> <p>In dui magna, posuere eget, vestibulum et, tempor auctor, justo. In ac felis quis tortor malesuada pretium.</p>',
                'created_at' => '2019-07-21 14:30:12',
                'updated_at' => '2019-07-21 14:30:12',
                'deleted_at' => NULL,
                'publish' => 0,
                'publish_from' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            11 => 
            array (
                'id' => 584,
                'user_id' => 2,
                'language_parent' => 6,
                'language' => 'en',
                'title' => '[EN] Multiple Colour Schemes',
                'customtags' => NULL,
                'iconalign' => 'left',
                'iconclass' => 'icon-game-controller',
                'linkurl' => '',
                'linktext' => '',
                'isglobal' => 0,
                'type' => 'icon',
                'hook' => 'home6',
                'template' => NULL,
                'sortorder' => 0,
                'usecache' => 0,
                'maxitems' => 0,
                'imgreq' => 0,
                'term' => '',
                'relentkey' => '',
                'slug' => 'en-multiple-colour-schemes',
                'slug_lock' => 0,
                'body' => '<p>[EN]</p> <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In dui magna posuere.</p>',
                'created_at' => '2019-07-21 14:30:12',
                'updated_at' => '2019-07-21 14:30:12',
                'deleted_at' => NULL,
                'publish' => 0,
                'publish_from' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            12 => 
            array (
                'id' => 585,
                'user_id' => 2,
                'language_parent' => 7,
                'language' => 'en',
                'title' => '[EN] Branding',
                'customtags' => NULL,
                'iconalign' => 'top',
                'iconclass' => 'icon-fire',
                'linkurl' => '',
                'linktext' => '',
                'isglobal' => 0,
                'type' => 'icon',
                'hook' => 'home8',
                'template' => NULL,
                'sortorder' => 0,
                'usecache' => 0,
                'maxitems' => 0,
                'imgreq' => 0,
                'term' => '',
                'relentkey' => '',
                'slug' => 'en-branding',
                'slug_lock' => 0,
                'body' => '<p>[EN]</p> <p>Donec pede justo fringilla vel aliquet nec vulputate eget arcu. In enim justo rhoncus ut imperdiet a venenatis vitae justo.</p>',
                'created_at' => '2019-07-21 14:30:12',
                'updated_at' => '2019-07-21 14:30:12',
                'deleted_at' => NULL,
                'publish' => 0,
                'publish_from' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            13 => 
            array (
                'id' => 586,
                'user_id' => 2,
                'language_parent' => 8,
                'language' => 'en',
                'title' => '[EN] Development',
                'customtags' => NULL,
                'iconalign' => 'top',
                'iconclass' => 'icon-wrench',
                'linkurl' => '',
                'linktext' => '',
                'isglobal' => 0,
                'type' => 'icon',
                'hook' => 'home9',
                'template' => NULL,
                'sortorder' => 0,
                'usecache' => 0,
                'maxitems' => 0,
                'imgreq' => 0,
                'term' => '',
                'relentkey' => '',
                'slug' => 'en-development',
                'slug_lock' => 0,
                'body' => '<p>[EN]</p> <p>Donec pede justo fringilla vel aliquet nec vulputate eget arcu. In enim justo rhoncus ut imperdiet a venenatis vitae justo.</p>',
                'created_at' => '2019-07-21 14:30:12',
                'updated_at' => '2019-07-21 14:30:12',
                'deleted_at' => NULL,
                'publish' => 0,
                'publish_from' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            14 => 
            array (
                'id' => 587,
                'user_id' => 2,
                'language_parent' => 9,
                'language' => 'en',
                'title' => '[EN] Maintenance',
                'customtags' => NULL,
                'iconalign' => 'top',
                'iconclass' => 'icon-earphones-alt',
                'linkurl' => '',
                'linktext' => '',
                'isglobal' => 0,
                'type' => 'icon',
                'hook' => 'home10',
                'template' => NULL,
                'sortorder' => 0,
                'usecache' => 0,
                'maxitems' => 0,
                'imgreq' => 0,
                'term' => '',
                'relentkey' => '',
                'slug' => 'en-maintenance',
                'slug_lock' => 0,
                'body' => '<p>[EN]</p> <p>Donec pede justo fringilla vel aliquet nec vulputate eget arcu. In enim justo rhoncus ut imperdiet a venenatis vitae justo.</p>',
                'created_at' => '2019-07-21 14:30:12',
                'updated_at' => '2019-07-21 14:30:12',
                'deleted_at' => NULL,
                'publish' => 0,
                'publish_from' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            15 => 
            array (
                'id' => 588,
                'user_id' => 2,
                'language_parent' => 12,
                'language' => 'en',
                'title' => '[EN] Alt Services',
                'customtags' => NULL,
                'iconalign' => '',
                'iconclass' => '',
                'linkurl' => '',
                'linktext' => '',
                'isglobal' => 0,
                'type' => 'text',
                'hook' => 'home7',
                'template' => NULL,
                'sortorder' => 0,
                'usecache' => 0,
                'maxitems' => 0,
                'imgreq' => 0,
                'term' => '',
                'relentkey' => '',
                'slug' => 'en-alt-services',
                'slug_lock' => 0,
                'body' => '<p>[EN]</p> <p>We provide a absolute list of superior digital services.</p>',
                'created_at' => '2019-07-21 14:30:12',
                'updated_at' => '2019-07-21 14:30:12',
                'deleted_at' => NULL,
                'publish' => 0,
                'publish_from' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            16 => 
            array (
                'id' => 589,
                'user_id' => 2,
                'language_parent' => 13,
                'language' => 'en',
                'title' => '[EN] Lorem ipsum',
                'customtags' => NULL,
                'iconalign' => '',
                'iconclass' => '',
                'linkurl' => '',
                'linktext' => '',
                'isglobal' => 0,
                'type' => 'text',
                'hook' => 'footer1',
                'template' => NULL,
                'sortorder' => 0,
                'usecache' => 0,
                'maxitems' => 0,
                'imgreq' => 0,
                'term' => '',
                'relentkey' => '',
                'slug' => 'en-lorem-ipsum',
                'slug_lock' => 0,
                'body' => '<p>[EN]</p> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam hendrerit felis in nibh pretium, quis dignissim eros condimentum.</p>',
                'created_at' => '2019-07-21 14:30:12',
                'updated_at' => '2019-07-21 14:30:12',
                'deleted_at' => NULL,
                'publish' => 0,
                'publish_from' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            17 => 
            array (
                'id' => 590,
                'user_id' => 2,
                'language_parent' => 14,
                'language' => 'en',
                'title' => '[EN] test',
                'customtags' => NULL,
                'iconalign' => '',
                'iconclass' => '',
                'linkurl' => '',
                'linktext' => '',
                'isglobal' => 0,
                'type' => 'text',
                'hook' => 'footer2',
                'template' => NULL,
                'sortorder' => 0,
                'usecache' => 0,
                'maxitems' => 0,
                'imgreq' => 0,
                'term' => '',
                'relentkey' => '',
                'slug' => 'en-test',
                'slug_lock' => 0,
                'body' => '<p>[EN]</p> ',
                'created_at' => '2019-07-21 14:30:12',
                'updated_at' => '2019-07-21 14:30:12',
                'deleted_at' => NULL,
                'publish' => 0,
                'publish_from' => NULL,
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            18 => 
            array (
                'id' => 591,
                'user_id' => 2,
                'language_parent' => NULL,
                'language' => 'nl',
                'title' => 'Our Team',
                'customtags' => '',
                'iconalign' => '',
                'iconclass' => '',
                'linkurl' => '',
                'linktext' => '',
                'isglobal' => 0,
                'type' => 'module',
                'hook' => 'content_bottom',
                'template' => '',
                'sortorder' => 20,
                'usecache' => 1,
                'maxitems' => 8,
                'imgreq' => 1,
                'term' => 'none',
                'relentkey' => 'team',
                'slug' => 'our-team',
                'slug_lock' => 0,
                'body' => '',
                'created_at' => '2019-08-10 15:03:30',
                'updated_at' => '2023-09-22 14:57:54',
                'deleted_at' => NULL,
                'publish' => 0,
                'publish_from' => '2019-08-10 00:00:00',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            19 => 
            array (
                'id' => 592,
                'user_id' => 2,
                'language_parent' => NULL,
                'language' => 'nl',
                'title' => 'News from our Development Team',
                'customtags' => '',
                'iconalign' => '',
                'iconclass' => '',
                'linkurl' => '',
                'linktext' => '',
                'isglobal' => 0,
                'type' => 'module',
                'hook' => 'content_bottom',
                'template' => 'team',
                'sortorder' => 0,
                'usecache' => 0,
                'maxitems' => 3,
                'imgreq' => 1,
                'term' => 'team-news',
                'relentkey' => 'blog',
                'slug' => 'blog-widget',
                'slug_lock' => 0,
                'body' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur efficitur, tellus et lobortis congue, nisl ante semper odio, in suscipit turpis neque vitae elit. Curabitur ultricies velit vitae nulla lacinia, id pulvinar nulla facilisis. Vivamus non augue vitae risus luctus convallis non quis elit. Sed aliquam, augue quis mollis sagittis, odio sem faucibus magna, non lobortis nulla odio id diam.</p>',
                'created_at' => '2019-08-19 13:46:58',
                'updated_at' => '2023-04-25 15:55:47',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2019-08-19 00:00:00',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            20 => 
            array (
                'id' => 593,
                'user_id' => 2,
                'language_parent' => NULL,
                'language' => 'nl',
                'title' => 'Socials',
                'customtags' => '',
                'iconalign' => '',
                'iconclass' => '',
                'linkurl' => '',
                'linktext' => '',
                'isglobal' => 1,
                'type' => 'text',
                'hook' => 'footer3',
                'template' => 'footerlinks',
                'sortorder' => 0,
                'usecache' => 0,
                'maxitems' => 0,
                'imgreq' => 0,
                'term' => '',
                'relentkey' => '',
                'slug' => 'socials',
                'slug_lock' => 0,
                'body' => '<div id="social-links" class="collapse d-lg-block" data-bs-parent="#footer-links">
<ul class="nav flex-column mb-8 mb-lg-0">
<li class="nav-item"><a class="nav-link d-inline-block px-0 pt-4 pb-8" href="#">Facebook</a></li>
<li class="nav-item"><a class="nav-link d-inline-block px-0 pt-4 pb-8" href="#">LinkedIn</a></li>
<li class="nav-item"><a class="nav-link d-inline-block px-0 pt-4 pb-8" href="#">Twitter</a></li>
<li class="nav-item"><a class="nav-link d-inline-block px-0 pt-4 pb-8" href="#">Instagram</a></li>
</ul>
</div>',
                'created_at' => '2023-03-12 12:49:11',
                'updated_at' => '2023-03-12 13:02:45',
                'deleted_at' => '2023-03-12 13:02:45',
                'publish' => 1,
                'publish_from' => '2023-03-12 00:00:00',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            21 => 
            array (
                'id' => 594,
                'user_id' => 2,
                'language_parent' => NULL,
                'language' => 'nl',
                'title' => 'What Our Clients Say About Us',
                'customtags' => '',
                'iconalign' => '',
                'iconclass' => '',
                'linkurl' => '',
                'linktext' => '',
                'isglobal' => 0,
                'type' => 'module',
                'hook' => 'content_bottom',
                'template' => 'about',
                'sortorder' => 10,
                'usecache' => 1,
                'maxitems' => 3,
                'imgreq' => 1,
                'term' => 'about',
                'relentkey' => 'testimonial',
                'slug' => 'what-our-clients-say-about-us',
                'slug_lock' => 0,
                'body' => '',
                'created_at' => '2023-03-12 18:33:04',
                'updated_at' => '2023-05-09 14:54:31',
                'deleted_at' => NULL,
                'publish' => 1,
                'publish_from' => '2023-03-12 18:37:00',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
            22 => 
            array (
                'id' => 595,
                'user_id' => 2,
                'language_parent' => NULL,
                'language' => 'nl',
                'title' => 'We Have Social Networks',
                'customtags' => '',
                'iconalign' => '',
                'iconclass' => '',
                'linkurl' => '',
                'linktext' => '',
                'isglobal' => 0,
                'type' => 'text',
                'hook' => 'content_bottom',
                'template' => 'about_social',
                'sortorder' => 30,
                'usecache' => 0,
                'maxitems' => 0,
                'imgreq' => 0,
                'term' => '',
                'relentkey' => '',
                'slug' => 'we-have-social-networks',
                'slug_lock' => 0,
                'body' => '',
                'created_at' => '2023-03-13 11:26:27',
                'updated_at' => '2023-05-11 16:58:45',
                'deleted_at' => NULL,
                'publish' => 0,
                'publish_from' => '2023-03-13 00:00:00',
                'locked_at' => NULL,
                'locked_by' => NULL,
            ),
        ));
        
        
    }
}