<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class LaraEntEntityCustomColumnsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('lara_ent_entity_custom_columns')->delete();
        
        \DB::table('lara_ent_entity_custom_columns')->insert(array (
            0 => 
            array (
                'id' => 1,
                'entity_id' => 3,
                'fieldtitle' => 'First Name',
                'fieldname' => 'firstname',
                'fieldtype' => 'string',
                'fieldhook' => 'before',
                'fielddata' => '',
                'primary' => 1,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 1,
                'field_lock' => 0,
            ),
            1 => 
            array (
                'id' => 4,
                'entity_id' => 3,
                'fieldtitle' => 'Middle Name',
                'fieldname' => 'middlename',
                'fieldtype' => 'string',
                'fieldhook' => 'before',
                'fielddata' => '',
                'primary' => 1,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 2,
                'field_lock' => 0,
            ),
            2 => 
            array (
                'id' => 5,
                'entity_id' => 2,
                'fieldtitle' => 'Source',
                'fieldname' => 'source',
                'fieldtype' => 'string',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 4,
                'field_lock' => 0,
            ),
            3 => 
            array (
                'id' => 6,
                'entity_id' => 2,
                'fieldtitle' => 'Location',
                'fieldname' => 'location',
                'fieldtype' => 'string',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'hidden',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 5,
                'field_lock' => 0,
            ),
            4 => 
            array (
                'id' => 13,
                'entity_id' => 17,
                'fieldtitle' => 'Start Date',
                'fieldname' => 'startdate',
                'fieldtype' => 'date',
                'fieldhook' => 'between',
                'fielddata' => '',
                'primary' => 1,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 12,
                'field_lock' => 0,
            ),
            5 => 
            array (
                'id' => 14,
                'entity_id' => 17,
                'fieldtitle' => 'Start Time',
                'fieldname' => 'starttime',
                'fieldtype' => 'time',
                'fieldhook' => 'between',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 13,
                'field_lock' => 0,
            ),
            6 => 
            array (
                'id' => 15,
                'entity_id' => 17,
                'fieldtitle' => 'End Date',
                'fieldname' => 'enddate',
                'fieldtype' => 'date',
                'fieldhook' => 'between',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 14,
                'field_lock' => 0,
            ),
            7 => 
            array (
                'id' => 16,
                'entity_id' => 17,
                'fieldtitle' => 'End Time',
                'fieldname' => 'endtime',
                'fieldtype' => 'time',
                'fieldhook' => 'between',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 15,
                'field_lock' => 0,
            ),
            8 => 
            array (
                'id' => 19,
                'entity_id' => 20,
                'fieldtitle' => 'Type',
                'fieldname' => 'type',
                'fieldtype' => 'selectone',
                'fieldhook' => 'after',
                'fielddata' => '{"0":"image","1":"caption","2":"payoff"}',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 18,
                'field_lock' => 0,
            ),
            9 => 
            array (
                'id' => 20,
                'entity_id' => 20,
                'fieldtitle' => 'Caption',
                'fieldname' => 'caption',
                'fieldtype' => 'text',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabledif',
                'condition_field' => 'type',
                'condition_operator' => 'isequal',
                'condition_value' => 'caption',
                'position' => 19,
                'field_lock' => 0,
            ),
            10 => 
            array (
                'id' => 21,
                'entity_id' => 20,
                'fieldtitle' => 'Payoff',
                'fieldname' => 'payoff',
                'fieldtype' => 'mcemin',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabledif',
                'condition_field' => 'type',
                'condition_operator' => 'isequal',
                'condition_value' => 'payoff',
                'position' => 22,
                'field_lock' => 0,
            ),
            11 => 
            array (
                'id' => 22,
                'entity_id' => 20,
                'fieldtitle' => 'Url',
                'fieldname' => 'url',
                'fieldtype' => 'string',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabledif',
                'condition_field' => 'type',
                'condition_operator' => 'isequal',
                'condition_value' => 'payoff',
                'position' => 23,
                'field_lock' => 0,
            ),
            12 => 
            array (
                'id' => 23,
                'entity_id' => 20,
                'fieldtitle' => 'Url Title',
                'fieldname' => 'urltitle',
                'fieldtype' => 'string',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabledif',
                'condition_field' => 'type',
                'condition_operator' => 'isequal',
                'condition_value' => 'payoff',
                'position' => 24,
                'field_lock' => 0,
            ),
            13 => 
            array (
                'id' => 24,
                'entity_id' => 20,
                'fieldtitle' => 'Url Text',
                'fieldname' => 'urltext',
                'fieldtype' => 'string',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabledif',
                'condition_field' => 'type',
                'condition_operator' => 'isequal',
                'condition_value' => 'payoff',
                'position' => 25,
                'field_lock' => 0,
            ),
            14 => 
            array (
                'id' => 33,
                'entity_id' => 1,
                'fieldtitle' => 'Menu Route',
                'fieldname' => 'menuroute',
                'fieldtype' => 'string',
                'fieldhook' => 'before',
                'fielddata' => '',
                'primary' => 1,
                'required' => 0,
                'fieldstate' => 'hidden',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 35,
                'field_lock' => 1,
            ),
            15 => 
            array (
                'id' => 34,
                'entity_id' => 27,
                'fieldtitle' => 'Hook',
                'fieldname' => 'hook',
                'fieldtype' => 'selectone',
                'fieldhook' => 'before',
                'fielddata' => '{"0":"content_top","1":"content_bottom","2":"home1","3":"home2","4":"home3","5":"home4","6":"home5","7":"home6","8":"home7","9":"home8","10":"home9","11":"home10","12":"footer1","13":"footer2","14":"footer3","15":"footer4"}',
                'primary' => 1,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 39,
                'field_lock' => 0,
            ),
            16 => 
            array (
                'id' => 37,
                'entity_id' => 27,
                'fieldtitle' => 'Icon class',
                'fieldname' => 'iconclass',
                'fieldtype' => 'string',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabledif',
                'condition_field' => 'type',
                'condition_operator' => 'isequal',
                'condition_value' => 'icon',
                'position' => 43,
                'field_lock' => 0,
            ),
            17 => 
            array (
                'id' => 40,
                'entity_id' => 27,
                'fieldtitle' => 'Icon align',
                'fieldname' => 'iconalign',
                'fieldtype' => 'selectone',
                'fieldhook' => 'after',
                'fielddata' => '{"0":"top","1":"left","2":"right"}',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabledif',
                'condition_field' => 'type',
                'condition_operator' => 'isequal',
                'condition_value' => 'icon',
                'position' => 44,
                'field_lock' => 0,
            ),
            18 => 
            array (
                'id' => 41,
                'entity_id' => 27,
                'fieldtitle' => 'Type',
                'fieldname' => 'type',
                'fieldtype' => 'selectone',
                'fieldhook' => 'before',
                'fielddata' => '{"0":"text","1":"icon","2":"feature","3":"module"}',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 40,
                'field_lock' => 0,
            ),
            19 => 
            array (
                'id' => 42,
                'entity_id' => 3,
                'fieldtitle' => 'Role',
                'fieldname' => 'role',
                'fieldtype' => 'string',
                'fieldhook' => 'between',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 83,
                'field_lock' => 0,
            ),
            20 => 
            array (
                'id' => 45,
                'entity_id' => 27,
                'fieldtitle' => 'Link text',
                'fieldname' => 'linktext',
                'fieldtype' => 'string',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 37,
                'field_lock' => 0,
            ),
            21 => 
            array (
                'id' => 46,
                'entity_id' => 27,
                'fieldtitle' => 'Link url',
                'fieldname' => 'linkurl',
                'fieldtype' => 'string',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 38,
                'field_lock' => 0,
            ),
            22 => 
            array (
                'id' => 47,
                'entity_id' => 29,
                'fieldtitle' => 'url',
                'fieldname' => 'url',
                'fieldtype' => 'string',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 47,
                'field_lock' => 0,
            ),
            23 => 
            array (
                'id' => 48,
                'entity_id' => 31,
                'fieldtitle' => 'Hook',
                'fieldname' => 'hook',
                'fieldtype' => 'selectone2one',
                'fieldhook' => 'after',
                'fielddata' => '{"0":"contact","1":"newsletter"}',
                'primary' => 1,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 39,
                'field_lock' => 0,
            ),
            24 => 
            array (
                'id' => 51,
                'entity_id' => 31,
                'fieldtitle' => 'Type',
                'fieldname' => 'type',
                'fieldtype' => 'selectone',
                'fieldhook' => 'after',
                'fielddata' => '{"0":"solid","1":"image","2":"parallax"}',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 40,
                'field_lock' => 0,
            ),
            25 => 
            array (
                'id' => 52,
                'entity_id' => 31,
                'fieldtitle' => 'Overlay color',
                'fieldname' => 'overlaycolor',
                'fieldtype' => 'selectone',
                'fieldhook' => 'after',
                'fielddata' => '{"0":"black","1":"brand"}',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 45,
                'field_lock' => 0,
            ),
            26 => 
            array (
                'id' => 53,
                'entity_id' => 31,
                'fieldtitle' => 'Overlay transparency',
                'fieldname' => 'overlaytransp',
                'fieldtype' => 'selectone',
                'fieldhook' => 'after',
                'fielddata' => '{"0":"0","1":"10","2":"20","3":"30","4":"40","5":"50","6":"60","7":"70","8":"80","9":"90"}',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 46,
                'field_lock' => 0,
            ),
            27 => 
            array (
                'id' => 54,
                'entity_id' => 31,
                'fieldtitle' => 'Link text',
                'fieldname' => 'linktext',
                'fieldtype' => 'string',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 37,
                'field_lock' => 0,
            ),
            28 => 
            array (
                'id' => 55,
                'entity_id' => 31,
                'fieldtitle' => 'Link url',
                'fieldname' => 'linkurl',
                'fieldtype' => 'string',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 38,
                'field_lock' => 0,
            ),
            29 => 
            array (
                'id' => 56,
                'entity_id' => 34,
                'fieldtitle' => 'Name',
                'fieldname' => 'name',
                'fieldtype' => 'string',
                'fieldhook' => 'default',
                'fielddata' => '',
                'primary' => 0,
                'required' => 1,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 48,
                'field_lock' => 0,
            ),
            30 => 
            array (
                'id' => 57,
                'entity_id' => 34,
                'fieldtitle' => 'Email',
                'fieldname' => 'email',
                'fieldtype' => 'email',
                'fieldhook' => 'default',
                'fielddata' => '',
                'primary' => 0,
                'required' => 1,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 49,
                'field_lock' => 0,
            ),
            31 => 
            array (
                'id' => 58,
                'entity_id' => 1,
                'fieldtitle' => 'ishome',
                'fieldname' => 'ishome',
                'fieldtype' => 'boolean',
                'fieldhook' => 'before',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'hidden',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 51,
                'field_lock' => 1,
            ),
            32 => 
            array (
                'id' => 62,
                'entity_id' => 41,
                'fieldtitle' => 'mystring',
                'fieldname' => 'mystring',
                'fieldtype' => 'string',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 1,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 52,
                'field_lock' => 0,
            ),
            33 => 
            array (
                'id' => 63,
                'entity_id' => 41,
                'fieldtitle' => 'mytext',
                'fieldname' => 'mytext',
                'fieldtype' => 'text',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 53,
                'field_lock' => 0,
            ),
            34 => 
            array (
                'id' => 64,
                'entity_id' => 41,
                'fieldtitle' => 'mymcefull',
                'fieldname' => 'mymcefull',
                'fieldtype' => 'mcefull',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 54,
                'field_lock' => 0,
            ),
            35 => 
            array (
                'id' => 65,
                'entity_id' => 41,
                'fieldtitle' => 'mymcemin',
                'fieldname' => 'mymcemin',
                'fieldtype' => 'mcemin',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 55,
                'field_lock' => 0,
            ),
            36 => 
            array (
                'id' => 67,
                'entity_id' => 41,
                'fieldtitle' => 'myemail',
                'fieldname' => 'myemail',
                'fieldtype' => 'email',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 56,
                'field_lock' => 0,
            ),
            37 => 
            array (
                'id' => 68,
                'entity_id' => 41,
                'fieldtitle' => 'mydatetime',
                'fieldname' => 'mydatetime',
                'fieldtype' => 'datetime',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 57,
                'field_lock' => 0,
            ),
            38 => 
            array (
                'id' => 69,
                'entity_id' => 41,
                'fieldtitle' => 'mydate',
                'fieldname' => 'mydate',
                'fieldtype' => 'date',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 58,
                'field_lock' => 0,
            ),
            39 => 
            array (
                'id' => 70,
                'entity_id' => 41,
                'fieldtitle' => 'mytime',
                'fieldname' => 'mytime',
                'fieldtype' => 'time',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 59,
                'field_lock' => 0,
            ),
            40 => 
            array (
                'id' => 71,
                'entity_id' => 41,
                'fieldtitle' => 'myinteger',
                'fieldname' => 'myinteger',
                'fieldtype' => 'integer',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 60,
                'field_lock' => 0,
            ),
            41 => 
            array (
                'id' => 72,
                'entity_id' => 41,
                'fieldtitle' => 'mydecimal2',
                'fieldname' => 'mydecimal2',
                'fieldtype' => 'string',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 62,
                'field_lock' => 0,
            ),
            42 => 
            array (
                'id' => 73,
                'entity_id' => 41,
                'fieldtitle' => 'mydecimal4',
                'fieldname' => 'mydecimal4',
                'fieldtype' => 'string',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 63,
                'field_lock' => 0,
            ),
            43 => 
            array (
                'id' => 74,
                'entity_id' => 41,
                'fieldtitle' => 'myboolean',
                'fieldname' => 'myboolean',
                'fieldtype' => 'boolean',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 64,
                'field_lock' => 0,
            ),
            44 => 
            array (
                'id' => 75,
                'entity_id' => 41,
                'fieldtitle' => 'myselectone',
                'fieldname' => 'myselectone',
                'fieldtype' => 'selectone',
                'fieldhook' => 'after',
                'fielddata' => '{"0":"option1","1":"option2","2":"option3"}',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 65,
                'field_lock' => 0,
            ),
            45 => 
            array (
                'id' => 76,
                'entity_id' => 41,
                'fieldtitle' => 'myselectone2one',
                'fieldname' => 'myselectone2one',
                'fieldtype' => 'selectone2one',
                'fieldhook' => 'after',
                'fielddata' => '{"0":"option1","1":"option2","2":"option3"}',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 66,
                'field_lock' => 0,
            ),
            46 => 
            array (
                'id' => 77,
                'entity_id' => 41,
                'fieldtitle' => 'mycustom',
                'fieldname' => 'mycustom',
                'fieldtype' => 'custom',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 67,
                'field_lock' => 0,
            ),
            47 => 
            array (
                'id' => 78,
                'entity_id' => 41,
                'fieldtitle' => 'myintunsigned',
                'fieldname' => 'myintunsigned',
                'fieldtype' => 'intunsigned',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 61,
                'field_lock' => 0,
            ),
            48 => 
            array (
                'id' => 845,
                'entity_id' => 18,
                'fieldtitle' => 'geo',
                'fieldname' => 'geolocation',
                'fieldtype' => 'geolocation',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 72,
                'field_lock' => 0,
            ),
            49 => 
            array (
                'id' => 846,
                'entity_id' => 18,
                'fieldtitle' => 'Latitude',
                'fieldname' => 'latitude',
                'fieldtype' => 'decimal108',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabledif',
                'condition_field' => 'geolocation',
                'condition_operator' => 'isequal',
                'condition_value' => 'manual',
                'position' => 73,
                'field_lock' => 1,
            ),
            50 => 
            array (
                'id' => 847,
                'entity_id' => 18,
                'fieldtitle' => 'Longitude',
                'fieldname' => 'longitude',
                'fieldtype' => 'decimal118',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabledif',
                'condition_field' => 'geolocation',
                'condition_operator' => 'isequal',
                'condition_value' => 'manual',
                'position' => 74,
                'field_lock' => 1,
            ),
            51 => 
            array (
                'id' => 848,
                'entity_id' => 18,
                'fieldtitle' => 'Address',
                'fieldname' => 'address',
                'fieldtype' => 'string',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 68,
                'field_lock' => 0,
            ),
            52 => 
            array (
                'id' => 849,
                'entity_id' => 18,
                'fieldtitle' => 'Postal Code',
                'fieldname' => 'pcode',
                'fieldtype' => 'string',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 69,
                'field_lock' => 0,
            ),
            53 => 
            array (
                'id' => 850,
                'entity_id' => 18,
                'fieldtitle' => 'City',
                'fieldname' => 'city',
                'fieldtype' => 'string',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 70,
                'field_lock' => 0,
            ),
            54 => 
            array (
                'id' => 851,
                'entity_id' => 18,
                'fieldtitle' => 'Country',
                'fieldname' => 'country',
                'fieldtype' => 'string',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 71,
                'field_lock' => 0,
            ),
            55 => 
            array (
                'id' => 854,
                'entity_id' => 20,
                'fieldtitle' => 'Overlay transparency',
                'fieldname' => 'overlaytransp',
                'fieldtype' => 'selectone',
                'fieldhook' => 'after',
                'fielddata' => '{"0":"0","1":"10","2":"20","3":"30","4":"40","5":"50","6":"60","7":"70","8":"80","9":"90"}',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabledif',
                'condition_field' => 'type',
                'condition_operator' => 'isequal',
                'condition_value' => 'payoff',
                'position' => 77,
                'field_lock' => 0,
            ),
            56 => 
            array (
                'id' => 855,
                'entity_id' => 34,
                'fieldtitle' => 'Comment',
                'fieldname' => 'comment',
                'fieldtype' => 'text',
                'fieldhook' => 'default',
                'fielddata' => '',
                'primary' => 1,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 79,
                'field_lock' => 0,
            ),
            57 => 
            array (
                'id' => 857,
                'entity_id' => 20,
                'fieldtitle' => 'Text Position',
                'fieldname' => 'textposition',
                'fieldtype' => 'selectone',
                'fieldhook' => 'after',
                'fielddata' => '{"0":"center","1":"left","2":"right"}',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabledif',
                'condition_field' => 'type',
                'condition_operator' => 'isequal',
                'condition_value' => 'payoff',
                'position' => 81,
                'field_lock' => 0,
            ),
            58 => 
            array (
                'id' => 858,
                'entity_id' => 20,
                'fieldtitle' => 'Overlay color',
                'fieldname' => 'overlaycolor',
                'fieldtype' => 'selectone',
                'fieldhook' => 'after',
                'fielddata' => '{"0":"black","1":"white","2":"primary"}',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabledif',
                'condition_field' => 'type',
                'condition_operator' => 'isequal',
                'condition_value' => 'payoff',
                'position' => 26,
                'field_lock' => 0,
            ),
            59 => 
            array (
                'id' => 859,
                'entity_id' => 20,
                'fieldtitle' => 'Overlay size',
                'fieldname' => 'overlaysize',
                'fieldtype' => 'selectone',
                'fieldhook' => 'after',
                'fielddata' => '{"0":"full","1":"block"}',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabledif',
                'condition_field' => 'type',
                'condition_operator' => 'isequal',
                'condition_value' => 'payoff',
                'position' => 78,
                'field_lock' => 0,
            ),
            60 => 
            array (
                'id' => 860,
                'entity_id' => 20,
                'fieldtitle' => 'Caption type',
                'fieldname' => 'captiontype',
                'fieldtype' => 'selectone',
                'fieldhook' => 'after',
                'fielddata' => '{"0":"block","1":"fade"}',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabledif',
                'condition_field' => 'type',
                'condition_operator' => 'isequal',
                'condition_value' => 'caption',
                'position' => 20,
                'field_lock' => 0,
            ),
            61 => 
            array (
                'id' => 861,
                'entity_id' => 2,
                'fieldtitle' => 'sticky',
                'fieldname' => 'sticky',
                'fieldtype' => 'boolean',
                'fieldhook' => 'between',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 3,
                'field_lock' => 0,
            ),
            62 => 
            array (
                'id' => 862,
                'entity_id' => 3,
                'fieldtitle' => 'email',
                'fieldname' => 'email',
                'fieldtype' => 'string',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 82,
                'field_lock' => 0,
            ),
            63 => 
            array (
                'id' => 880,
                'entity_id' => 27,
                'fieldtitle' => 'relentkey',
                'fieldname' => 'relentkey',
                'fieldtype' => 'custom',
                'fieldhook' => 'between',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabledif',
                'condition_field' => 'type',
                'condition_operator' => 'isequal',
                'condition_value' => 'module',
                'position' => 100,
                'field_lock' => 0,
            ),
            64 => 
            array (
                'id' => 881,
                'entity_id' => 27,
                'fieldtitle' => 'term',
                'fieldname' => 'term',
                'fieldtype' => 'custom',
                'fieldhook' => 'between',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabledif',
                'condition_field' => 'type',
                'condition_operator' => 'isequal',
                'condition_value' => 'module',
                'position' => 101,
                'field_lock' => 0,
            ),
            65 => 
            array (
                'id' => 882,
                'entity_id' => 27,
                'fieldtitle' => 'imgreq',
                'fieldname' => 'imgreq',
                'fieldtype' => 'boolean',
                'fieldhook' => 'between',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabledif',
                'condition_field' => 'type',
                'condition_operator' => 'isequal',
                'condition_value' => 'module',
                'position' => 102,
                'field_lock' => 0,
            ),
            66 => 
            array (
                'id' => 883,
                'entity_id' => 27,
                'fieldtitle' => 'maxitems',
                'fieldname' => 'maxitems',
                'fieldtype' => 'intunsigned',
                'fieldhook' => 'between',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabledif',
                'condition_field' => 'type',
                'condition_operator' => 'isequal',
                'condition_value' => 'module',
                'position' => 103,
                'field_lock' => 0,
            ),
            67 => 
            array (
                'id' => 884,
                'entity_id' => 27,
                'fieldtitle' => 'usecache',
                'fieldname' => 'usecache',
                'fieldtype' => 'boolean',
                'fieldhook' => 'between',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 104,
                'field_lock' => 0,
            ),
            68 => 
            array (
                'id' => 885,
                'entity_id' => 27,
                'fieldtitle' => 'sortorder',
                'fieldname' => 'sortorder',
                'fieldtype' => 'intunsigned',
                'fieldhook' => 'between',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => 'NULL',
                'condition_operator' => 'NULL',
                'condition_value' => 'NULL',
                'position' => 105,
                'field_lock' => 0,
            ),
            69 => 
            array (
                'id' => 886,
                'entity_id' => 27,
                'fieldtitle' => 'template',
                'fieldname' => 'template',
                'fieldtype' => 'custom',
                'fieldhook' => 'between',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 106,
                'field_lock' => 0,
            ),
            70 => 
            array (
                'id' => 887,
                'entity_id' => 27,
                'fieldtitle' => 'isglobal',
                'fieldname' => 'isglobal',
                'fieldtype' => 'boolean',
                'fieldhook' => 'before',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 107,
                'field_lock' => 0,
            ),
            71 => 
            array (
                'id' => 888,
                'entity_id' => 27,
                'fieldtitle' => 'customtags',
                'fieldname' => 'customtags',
                'fieldtype' => 'string',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabledif',
                'condition_field' => 'type',
                'condition_operator' => 'isequal',
                'condition_value' => 'feature || featuresmall',
                'position' => 108,
                'field_lock' => 0,
            ),
            72 => 
            array (
                'id' => 889,
                'entity_id' => 69,
                'fieldtitle' => 'myname',
                'fieldname' => 'myname',
                'fieldtype' => 'string',
                'fieldhook' => 'default',
                'fielddata' => '',
                'primary' => 0,
                'required' => 1,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 110,
                'field_lock' => 0,
            ),
            73 => 
            array (
                'id' => 890,
                'entity_id' => 69,
                'fieldtitle' => 'myemail',
                'fieldname' => 'myemail',
                'fieldtype' => 'email',
                'fieldhook' => 'default',
                'fielddata' => '',
                'primary' => 0,
                'required' => 1,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 111,
                'field_lock' => 0,
            ),
            74 => 
            array (
                'id' => 891,
                'entity_id' => 70,
                'fieldtitle' => 'role',
                'fieldname' => 'role',
                'fieldtype' => 'string',
                'fieldhook' => 'between',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 112,
                'field_lock' => 0,
            ),
            75 => 
            array (
                'id' => 892,
                'entity_id' => 70,
                'fieldtitle' => 'youtubecode',
                'fieldname' => 'youtubecode',
                'fieldtype' => 'video',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 113,
                'field_lock' => 0,
            ),
            76 => 
            array (
                'id' => 893,
                'entity_id' => 71,
                'fieldtitle' => 'role',
                'fieldname' => 'role',
                'fieldtype' => 'string',
                'fieldhook' => 'between',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 114,
                'field_lock' => 0,
            ),
            77 => 
            array (
                'id' => 899,
                'entity_id' => 69,
                'fieldtitle' => 'myboolean',
                'fieldname' => 'myboolean',
                'fieldtype' => 'boolean',
                'fieldhook' => 'default',
                'fielddata' => '',
                'primary' => 0,
                'required' => 1,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 119,
                'field_lock' => 0,
            ),
            78 => 
            array (
                'id' => 900,
                'entity_id' => 85,
                'fieldtitle' => 'mystring',
                'fieldname' => 'mystring',
                'fieldtype' => 'string',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 1,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 52,
                'field_lock' => 0,
            ),
            79 => 
            array (
                'id' => 901,
                'entity_id' => 85,
                'fieldtitle' => 'mytext',
                'fieldname' => 'mytext',
                'fieldtype' => 'text',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 53,
                'field_lock' => 0,
            ),
            80 => 
            array (
                'id' => 902,
                'entity_id' => 85,
                'fieldtitle' => 'mymcefull',
                'fieldname' => 'mymcefull',
                'fieldtype' => 'mcefull',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 54,
                'field_lock' => 0,
            ),
            81 => 
            array (
                'id' => 903,
                'entity_id' => 85,
                'fieldtitle' => 'mymcemin',
                'fieldname' => 'mymcemin',
                'fieldtype' => 'mcemin',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 55,
                'field_lock' => 0,
            ),
            82 => 
            array (
                'id' => 904,
                'entity_id' => 85,
                'fieldtitle' => 'myemail',
                'fieldname' => 'myemail',
                'fieldtype' => 'email',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 56,
                'field_lock' => 0,
            ),
            83 => 
            array (
                'id' => 905,
                'entity_id' => 85,
                'fieldtitle' => 'mydatetime',
                'fieldname' => 'mydatetime',
                'fieldtype' => 'datetime',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 57,
                'field_lock' => 0,
            ),
            84 => 
            array (
                'id' => 906,
                'entity_id' => 85,
                'fieldtitle' => 'mydate',
                'fieldname' => 'mydate',
                'fieldtype' => 'date',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 58,
                'field_lock' => 0,
            ),
            85 => 
            array (
                'id' => 907,
                'entity_id' => 85,
                'fieldtitle' => 'mytime',
                'fieldname' => 'mytime',
                'fieldtype' => 'time',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 59,
                'field_lock' => 0,
            ),
            86 => 
            array (
                'id' => 908,
                'entity_id' => 85,
                'fieldtitle' => 'myinteger',
                'fieldname' => 'myinteger',
                'fieldtype' => 'integer',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 60,
                'field_lock' => 0,
            ),
            87 => 
            array (
                'id' => 909,
                'entity_id' => 85,
                'fieldtitle' => 'mydecimal2',
                'fieldname' => 'mydecimal2',
                'fieldtype' => 'decimal142',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 62,
                'field_lock' => 0,
            ),
            88 => 
            array (
                'id' => 910,
                'entity_id' => 85,
                'fieldtitle' => 'mydecimal4',
                'fieldname' => 'mydecimal4',
                'fieldtype' => 'decimal164',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 63,
                'field_lock' => 0,
            ),
            89 => 
            array (
                'id' => 911,
                'entity_id' => 85,
                'fieldtitle' => 'myboolean',
                'fieldname' => 'myboolean',
                'fieldtype' => 'boolean',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 64,
                'field_lock' => 0,
            ),
            90 => 
            array (
                'id' => 912,
                'entity_id' => 85,
                'fieldtitle' => 'myselectone',
                'fieldname' => 'myselectone',
                'fieldtype' => 'selectone',
                'fieldhook' => 'after',
                'fielddata' => '{"0":"option1","1":"option2","2":"option3"}',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 65,
                'field_lock' => 0,
            ),
            91 => 
            array (
                'id' => 913,
                'entity_id' => 85,
                'fieldtitle' => 'myselectone2one',
                'fieldname' => 'myselectone2one',
                'fieldtype' => 'selectone2one',
                'fieldhook' => 'after',
                'fielddata' => '{"0":"option1","1":"option2","2":"option3"}',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 66,
                'field_lock' => 0,
            ),
            92 => 
            array (
                'id' => 914,
                'entity_id' => 85,
                'fieldtitle' => 'mycustom',
                'fieldname' => 'mycustom',
                'fieldtype' => 'custom',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 67,
                'field_lock' => 0,
            ),
            93 => 
            array (
                'id' => 915,
                'entity_id' => 85,
                'fieldtitle' => 'myintunsigned',
                'fieldname' => 'myintunsigned',
                'fieldtype' => 'intunsigned',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 61,
                'field_lock' => 0,
            ),
            94 => 
            array (
                'id' => 916,
                'entity_id' => 1,
                'fieldtitle' => 'template',
                'fieldname' => 'template',
                'fieldtype' => 'selectone',
                'fieldhook' => 'after',
                'fielddata' => '{"0":"standard","1":"featured_left","2":"featured_left_responsive","3":"featured_right","4":"featured_right_responsive"}',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 120,
                'field_lock' => 0,
            ),
            95 => 
            array (
                'id' => 917,
                'entity_id' => 71,
                'fieldtitle' => 'quoteshort',
                'fieldname' => 'quoteshort',
                'fieldtype' => 'string',
                'fieldhook' => 'between',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 121,
                'field_lock' => 0,
            ),
            96 => 
            array (
                'id' => 918,
                'entity_id' => 71,
                'fieldtitle' => 'stars',
                'fieldname' => 'stars',
                'fieldtype' => 'selectone',
                'fieldhook' => 'after',
                'fielddata' => '{"0":"1","1":"2","2":"3","3":"4","4":"5"}',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 122,
                'field_lock' => 0,
            ),
            97 => 
            array (
                'id' => 919,
                'entity_id' => 20,
                'fieldtitle' => 'subtitle',
                'fieldname' => 'subtitle',
                'fieldtype' => 'string',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabledif',
                'condition_field' => 'type',
                'condition_operator' => 'isequal',
                'condition_value' => 'payoff',
                'position' => 21,
                'field_lock' => 0,
            ),
            98 => 
            array (
                'id' => 920,
                'entity_id' => 3,
                'fieldtitle' => 'facebook',
                'fieldname' => 'facebook',
                'fieldtype' => 'string',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 123,
                'field_lock' => 0,
            ),
            99 => 
            array (
                'id' => 921,
                'entity_id' => 3,
                'fieldtitle' => 'twitter',
                'fieldname' => 'twitter',
                'fieldtype' => 'string',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 124,
                'field_lock' => 0,
            ),
            100 => 
            array (
                'id' => 922,
                'entity_id' => 3,
                'fieldtitle' => 'linkedin',
                'fieldname' => 'linkedin',
                'fieldtype' => 'string',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 125,
                'field_lock' => 0,
            ),
            101 => 
            array (
                'id' => 957,
                'entity_id' => 34,
                'fieldtitle' => 'telephone',
                'fieldname' => 'telephone',
                'fieldtype' => 'string',
                'fieldhook' => 'default',
                'fielddata' => '',
                'primary' => 0,
                'required' => 1,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 50,
                'field_lock' => 0,
            ),
            102 => 
            array (
                'id' => 958,
                'entity_id' => 69,
                'fieldtitle' => 'mycomment',
                'fieldname' => 'mycomment',
                'fieldtype' => 'text',
                'fieldhook' => 'default',
                'fielddata' => '',
                'primary' => 0,
                'required' => 1,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 128,
                'field_lock' => 0,
            ),
            103 => 
            array (
                'id' => 959,
                'entity_id' => 69,
                'fieldtitle' => 'myselect',
                'fieldname' => 'myselect',
                'fieldtype' => 'selectone',
                'fieldhook' => 'default',
                'fielddata' => '{"0":"one","1":"two","2":"three"}',
                'primary' => 0,
                'required' => 1,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 129,
                'field_lock' => 0,
            ),
            104 => 
            array (
                'id' => 960,
                'entity_id' => 69,
                'fieldtitle' => 'myradio',
                'fieldname' => 'myradio',
                'fieldtype' => 'radio',
                'fieldhook' => 'default',
                'fielddata' => '{"0":"four","1":"five","2":"six"}',
                'primary' => 0,
                'required' => 1,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 130,
                'field_lock' => 0,
            ),
            105 => 
            array (
                'id' => 961,
                'entity_id' => 69,
                'fieldtitle' => 'myyesno',
                'fieldname' => 'myyesno',
                'fieldtype' => 'yesno',
                'fieldhook' => 'default',
                'fielddata' => '',
                'primary' => 0,
                'required' => 1,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 131,
                'field_lock' => 0,
            ),
            106 => 
            array (
                'id' => 962,
                'entity_id' => 69,
                'fieldtitle' => 'mydate',
                'fieldname' => 'mydate',
                'fieldtype' => 'date',
                'fieldhook' => 'default',
                'fielddata' => '',
                'primary' => 0,
                'required' => 1,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 132,
                'field_lock' => 0,
            ),
            107 => 
            array (
                'id' => 963,
                'entity_id' => 41,
                'fieldtitle' => 'mycolor',
                'fieldname' => 'mycolor',
                'fieldtype' => 'color',
                'fieldhook' => 'after',
                'fielddata' => '',
                'primary' => 0,
                'required' => 0,
                'fieldstate' => 'enabled',
                'condition_field' => NULL,
                'condition_operator' => NULL,
                'condition_value' => NULL,
                'position' => 133,
                'field_lock' => 0,
            ),
        ));
        
        
    }
}