<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class LaraEntEntityViewsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('lara_ent_entity_views')->delete();
        
        \DB::table('lara_ent_entity_views')->insert(array (
            0 => 
            array (
                'id' => 101,
                'entity_id' => 1,
                'title' => 'Page Show',
                'method' => 'show',
                'filename' => 'show',
                'type' => '_single',
                'showtags' => 'none',
                'paginate' => 0,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2018-01-27 16:21:32',
            ),
            1 => 
            array (
                'id' => 201,
                'entity_id' => 2,
                'title' => 'News Index',
                'method' => 'index',
                'filename' => 'index',
                'type' => 'list',
                'showtags' => 'none',
                'paginate' => 6,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2023-03-14 11:52:14',
            ),
            2 => 
            array (
                'id' => 301,
                'entity_id' => 3,
                'title' => 'Team Index',
                'method' => 'index',
                'filename' => 'index',
                'type' => 'grid4',
                'showtags' => 'none',
                'paginate' => 0,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2023-03-16 14:53:27',
            ),
            3 => 
            array (
                'id' => 303,
                'entity_id' => 2,
                'title' => 'News Single',
                'method' => 'show',
                'filename' => 'show',
                'type' => '_single',
                'showtags' => 'none',
                'paginate' => 0,
                'infinite' => 0,
                'prevnext' => 1,
                'publish' => 1,
                'created_at' => '2017-12-30 13:33:34',
                'updated_at' => '2020-12-23 19:47:13',
            ),
            4 => 
            array (
                'id' => 304,
                'entity_id' => 3,
                'title' => 'Team Show',
                'method' => 'show',
                'filename' => 'show',
                'type' => '_single',
                'showtags' => 'none',
                'paginate' => 0,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
                'created_at' => NULL,
                'updated_at' => '2018-01-25 18:52:10',
            ),
            5 => 
            array (
                'id' => 307,
                'entity_id' => 17,
                'title' => 'Event index',
                'method' => 'index',
                'filename' => 'index',
                'type' => 'list',
                'showtags' => 'none',
                'paginate' => 0,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
                'created_at' => '2018-01-08 11:40:35',
                'updated_at' => '2018-03-23 14:26:27',
            ),
            6 => 
            array (
                'id' => 308,
                'entity_id' => 17,
                'title' => 'Event show',
                'method' => 'show',
                'filename' => 'show',
                'type' => '_single',
                'showtags' => 'none',
                'paginate' => 0,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
                'created_at' => '2018-01-08 11:40:46',
                'updated_at' => '2018-03-23 14:26:27',
            ),
            7 => 
            array (
                'id' => 309,
                'entity_id' => 34,
                'title' => 'ContactForm',
                'method' => 'form',
                'filename' => 'form',
                'type' => '_form',
                'showtags' => 'none',
                'paginate' => 0,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
                'created_at' => '2018-01-15 21:14:03',
                'updated_at' => '2020-03-09 14:04:39',
            ),
            8 => 
            array (
                'id' => 314,
                'entity_id' => 41,
                'title' => 'Product Index',
                'method' => 'index',
                'filename' => 'index',
                'type' => 'list',
                'showtags' => 'none',
                'paginate' => 0,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 0,
                'created_at' => '2018-02-21 09:34:20',
                'updated_at' => '2018-02-21 09:34:20',
            ),
            9 => 
            array (
                'id' => 315,
                'entity_id' => 41,
                'title' => 'Product Show',
                'method' => 'show',
                'filename' => 'show',
                'type' => '_single',
                'showtags' => 'none',
                'paginate' => 0,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 0,
                'created_at' => '2018-02-21 09:34:33',
                'updated_at' => '2018-02-21 09:34:33',
            ),
            10 => 
            array (
                'id' => 316,
                'entity_id' => 42,
                'title' => 'Gallery Index',
                'method' => 'index',
                'filename' => 'index',
                'type' => 'grid3',
                'showtags' => 'none',
                'paginate' => 12,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
                'created_at' => '2018-04-20 08:47:04',
                'updated_at' => '2018-04-20 08:47:20',
            ),
            11 => 
            array (
                'id' => 317,
                'entity_id' => 42,
                'title' => 'Gallery Show',
                'method' => 'show',
                'filename' => 'show',
                'type' => '_single',
                'showtags' => 'none',
                'paginate' => 0,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
                'created_at' => '2018-04-20 08:47:41',
                'updated_at' => '2018-04-20 08:47:49',
            ),
            12 => 
            array (
                'id' => 318,
                'entity_id' => 43,
                'title' => 'Video Index',
                'method' => 'index',
                'filename' => 'index',
                'type' => 'list',
                'showtags' => 'none',
                'paginate' => 12,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
                'created_at' => '2018-04-20 08:54:11',
                'updated_at' => '2021-10-18 15:51:23',
            ),
            13 => 
            array (
                'id' => 319,
                'entity_id' => 43,
                'title' => 'Video Show',
                'method' => 'show',
                'filename' => 'show',
                'type' => '_single',
                'showtags' => 'none',
                'paginate' => 0,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
                'created_at' => '2018-04-20 08:54:39',
                'updated_at' => '2018-04-20 08:54:44',
            ),
            14 => 
            array (
                'id' => 320,
                'entity_id' => 44,
                'title' => 'Docs Index',
                'method' => 'index',
                'filename' => 'index',
                'type' => 'list',
                'showtags' => '_sortbytaxonomy',
                'paginate' => 0,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
                'created_at' => '2018-04-20 08:58:16',
                'updated_at' => '2021-01-09 15:00:48',
            ),
            15 => 
            array (
                'id' => 321,
                'entity_id' => 44,
                'title' => 'Docs Show',
                'method' => 'show',
                'filename' => 'show',
                'type' => '_single',
                'showtags' => 'none',
                'paginate' => 0,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
                'created_at' => '2018-04-20 08:58:24',
                'updated_at' => '2018-04-20 08:58:42',
            ),
            16 => 
            array (
                'id' => 322,
                'entity_id' => 69,
                'title' => 'Classicform',
                'method' => 'form',
                'filename' => 'form',
                'type' => '_form',
                'showtags' => 'none',
                'paginate' => 0,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
                'created_at' => '2019-12-17 09:27:50',
                'updated_at' => '2019-12-17 09:27:50',
            ),
            17 => 
            array (
                'id' => 323,
                'entity_id' => 70,
                'title' => 'Story Index',
                'method' => 'index',
                'filename' => 'index',
                'type' => 'list',
                'showtags' => 'none',
                'paginate' => 10,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
                'created_at' => '2020-06-17 16:35:30',
                'updated_at' => '2020-06-17 16:35:50',
            ),
            18 => 
            array (
                'id' => 324,
                'entity_id' => 70,
                'title' => 'Story Show',
                'method' => 'show',
                'filename' => 'show',
                'type' => '_single',
                'showtags' => 'none',
                'paginate' => 0,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
                'created_at' => '2020-06-17 16:35:40',
                'updated_at' => '2020-06-17 16:35:50',
            ),
            19 => 
            array (
                'id' => 325,
                'entity_id' => 71,
                'title' => 'Testimonial Index',
                'method' => 'index',
                'filename' => 'index',
                'type' => 'list',
                'showtags' => 'none',
                'paginate' => 0,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
                'created_at' => '2020-06-25 10:00:40',
                'updated_at' => '2023-03-11 13:18:06',
            ),
            20 => 
            array (
                'id' => 326,
                'entity_id' => 71,
                'title' => 'Testimonial Show',
                'method' => 'show',
                'filename' => 'show',
                'type' => '_single',
                'showtags' => 'none',
                'paginate' => 0,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
                'created_at' => '2020-06-25 10:00:52',
                'updated_at' => '2023-03-11 13:18:06',
            ),
            21 => 
            array (
                'id' => 327,
                'entity_id' => 18,
                'title' => 'Location Index',
                'method' => 'index',
                'filename' => 'index',
                'type' => 'list',
                'showtags' => 'none',
                'paginate' => 0,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
                'created_at' => '2020-10-03 19:37:02',
                'updated_at' => '2020-10-03 19:46:18',
            ),
            22 => 
            array (
                'id' => 328,
                'entity_id' => 18,
                'title' => 'Location Show',
                'method' => 'show',
                'filename' => 'show',
                'type' => '_single',
                'showtags' => 'none',
                'paginate' => 0,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
                'created_at' => '2020-10-03 19:46:33',
                'updated_at' => '2020-10-03 19:46:40',
            ),
            23 => 
            array (
                'id' => 331,
                'entity_id' => 85,
                'title' => 'City Index',
                'method' => 'index',
                'filename' => 'index',
                'type' => 'grid3',
                'showtags' => 'none',
                'paginate' => 6,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
                'created_at' => '2020-12-23 12:23:16',
                'updated_at' => '2020-12-23 12:23:47',
            ),
            24 => 
            array (
                'id' => 332,
                'entity_id' => 85,
                'title' => 'City Show',
                'method' => 'show',
                'filename' => 'show',
                'type' => '_single',
                'showtags' => 'none',
                'paginate' => 0,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
                'created_at' => '2020-12-23 12:23:27',
                'updated_at' => '2020-12-23 12:23:47',
            ),
            25 => 
            array (
                'id' => 333,
                'entity_id' => 86,
                'title' => 'Services Index',
                'method' => 'index',
                'filename' => 'index',
                'type' => 'list',
                'showtags' => 'filterbytaxonomy',
                'paginate' => 0,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
                'created_at' => '2023-03-16 15:00:17',
                'updated_at' => '2023-03-20 17:27:51',
            ),
            26 => 
            array (
                'id' => 334,
                'entity_id' => 86,
                'title' => 'Services Show',
                'method' => 'show',
                'filename' => 'show',
                'type' => '_single',
                'showtags' => 'none',
                'paginate' => 0,
                'infinite' => 0,
                'prevnext' => 0,
                'publish' => 1,
                'created_at' => '2023-03-16 15:00:27',
                'updated_at' => '2023-03-16 15:00:27',
            ),
        ));
        
        
    }
}