<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class LaraSysSettingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('lara_sys_settings')->delete();
        
        \DB::table('lara_sys_settings')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => 'Company Name',
                'cgroup' => 'company',
                'key' => 'company_name',
                'value' => 'Firmaq Media',
                'locked_by_admin' => 1,
                'created_at' => '2017-10-17 15:44:37',
                'updated_at' => '2023-05-08 15:36:47',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 2,
            ),
            1 => 
            array (
                'id' => 2,
                'title' => 'Company Street',
                'cgroup' => 'company',
                'key' => 'company_street',
                'value' => 'Schipholweg',
                'locked_by_admin' => 0,
                'created_at' => '2017-10-17 17:37:10',
                'updated_at' => '2023-04-16 20:18:56',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 4,
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'Company Email Address',
                'cgroup' => 'company',
                'key' => 'company_email',
                'value' => 'info@firmaq.nl',
                'locked_by_admin' => 1,
                'created_at' => '2017-10-17 17:53:53',
                'updated_at' => '2018-01-24 12:40:51',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 3,
            ),
            3 => 
            array (
                'id' => 5,
                'title' => 'Translation File Sync',
                'cgroup' => 'system',
                'key' => 'translation_file_sync',
                'value' => '2023-09-22 11:01:34',
                'locked_by_admin' => 1,
                'created_at' => '2017-10-20 12:59:00',
                'updated_at' => '2023-09-22 11:01:34',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 1,
            ),
            4 => 
            array (
                'id' => 6,
                'title' => 'Company Street Nr',
                'cgroup' => 'company',
                'key' => 'company_street_nr',
                'value' => '66',
                'locked_by_admin' => 0,
                'created_at' => '2018-01-22 09:48:07',
                'updated_at' => '2023-02-10 20:29:45',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 5,
            ),
            5 => 
            array (
                'id' => 7,
                'title' => 'Company Postal Code',
                'cgroup' => 'company',
                'key' => 'company_pcode',
                'value' => '2035LB',
                'locked_by_admin' => 0,
                'created_at' => '2018-01-24 12:41:38',
                'updated_at' => '2023-03-17 15:45:55',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 6,
            ),
            6 => 
            array (
                'id' => 8,
                'title' => 'Company City',
                'cgroup' => 'company',
                'key' => 'company_city',
                'value' => 'Haarlem',
                'locked_by_admin' => 0,
                'created_at' => '2018-01-24 12:42:00',
                'updated_at' => '2023-02-10 20:30:06',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 7,
            ),
            7 => 
            array (
                'id' => 9,
                'title' => 'Company Telephone',
                'cgroup' => 'company',
                'key' => 'company_telephone',
                'value' => '085 2006261',
                'locked_by_admin' => 0,
                'created_at' => '2018-01-24 12:42:43',
                'updated_at' => '2021-11-10 17:08:09',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 10,
            ),
            8 => 
            array (
                'id' => 10,
                'title' => 'Company Region',
                'cgroup' => 'company',
                'key' => 'company_region',
                'value' => 'Noord-Holland',
                'locked_by_admin' => 0,
                'created_at' => '2018-01-24 12:43:29',
                'updated_at' => '2019-12-18 12:52:15',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 8,
            ),
            9 => 
            array (
                'id' => 11,
                'title' => 'Company Country',
                'cgroup' => 'company',
                'key' => 'company_country',
                'value' => 'Nederland',
                'locked_by_admin' => 1,
                'created_at' => '2018-01-24 12:43:50',
                'updated_at' => '2018-01-24 12:43:58',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 9,
            ),
            10 => 
            array (
                'id' => 12,
                'title' => 'google_analytics_sync',
                'cgroup' => 'system',
                'key' => 'google_analytics_sync',
                'value' => '2023-08-23 11:14:45',
                'locked_by_admin' => 1,
                'created_at' => '2018-05-30 14:14:21',
                'updated_at' => '2023-08-23 11:14:45',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 11,
            ),
            11 => 
            array (
                'id' => 13,
                'title' => 'Google Analytics 4 ID',
                'cgroup' => 'company',
                'key' => 'ga4_id',
                'value' => 'G-P2VMZDGC1Z',
                'locked_by_admin' => 1,
                'created_at' => '2018-05-25 12:00:00',
                'updated_at' => '2023-09-21 11:15:58',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 23,
            ),
            12 => 
            array (
                'id' => 14,
                'title' => 'AddThis ID',
                'cgroup' => 'company',
                'key' => 'addthis_id',
                'value' => 'ra-',
                'locked_by_admin' => 1,
                'created_at' => '2018-05-25 12:00:00',
                'updated_at' => '2023-02-10 20:28:37',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 24,
            ),
            13 => 
            array (
                'id' => 15,
                'title' => 'Lara Version',
                'cgroup' => 'system',
                'key' => 'lara_db_version',
                'value' => '7.5.46',
                'locked_by_admin' => 1,
                'created_at' => '2018-06-12 11:18:52',
                'updated_at' => '2023-09-20 15:26:58',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 25,
            ),
            14 => 
            array (
                'id' => 16,
                'title' => 'Company Latitude',
                'cgroup' => 'company',
                'key' => 'company_latitude',
                'value' => '52.3700304',
                'locked_by_admin' => 1,
                'created_at' => '2018-06-18 14:01:02',
                'updated_at' => '2023-03-17 15:48:11',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 26,
            ),
            15 => 
            array (
                'id' => 17,
                'title' => 'Company Longitude',
                'cgroup' => 'company',
                'key' => 'company_longitude',
                'value' => '4.6454777',
                'locked_by_admin' => 1,
                'created_at' => '2018-06-18 14:01:18',
                'updated_at' => '2023-03-17 15:48:11',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 27,
            ),
            16 => 
            array (
                'id' => 18,
                'title' => 'Company Url',
                'cgroup' => 'company',
                'key' => 'company_url',
                'value' => NULL,
                'locked_by_admin' => 1,
                'created_at' => '2018-06-18 14:01:31',
                'updated_at' => '2023-02-10 20:27:48',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 28,
            ),
            17 => 
            array (
                'id' => 19,
                'title' => 'Google Maps Zoom',
                'cgroup' => 'general',
                'key' => 'google_maps_zoom',
                'value' => '15',
                'locked_by_admin' => 1,
                'created_at' => '2018-06-18 14:04:34',
                'updated_at' => '2018-06-18 14:07:50',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 29,
            ),
            18 => 
            array (
                'id' => 20,
                'title' => 'lara_cleanup_orphans',
                'cgroup' => 'system',
                'key' => 'lara_cleanup_orphans',
                'value' => '2020-05-19 14:26:14',
                'locked_by_admin' => 1,
                'created_at' => '2019-07-19 10:47:25',
                'updated_at' => '2020-05-19 14:26:14',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 30,
            ),
            19 => 
            array (
                'id' => 21,
                'title' => 'Company Telephone Clean',
                'cgroup' => 'company',
                'key' => 'company_telephone_clean',
                'value' => NULL,
                'locked_by_admin' => 1,
                'created_at' => '2019-07-21 18:50:40',
                'updated_at' => '2019-07-21 18:54:45',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 31,
            ),
            20 => 
            array (
                'id' => 22,
                'title' => 'Google Tag manager ID',
                'cgroup' => 'company',
                'key' => 'google_tagmanager_id',
                'value' => NULL,
                'locked_by_admin' => 1,
                'created_at' => '2019-08-12 18:53:46',
                'updated_at' => '2023-02-10 20:27:53',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 32,
            ),
            21 => 
            array (
                'id' => 27,
                'title' => 'OpenGraph Type',
                'cgroup' => 'opengraph',
                'key' => 'og_type',
                'value' => 'website',
                'locked_by_admin' => 1,
                'created_at' => '2019-10-03 20:52:19',
                'updated_at' => '2019-10-18 12:36:50',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 114,
            ),
            22 => 
            array (
                'id' => 28,
                'title' => 'OpenGraph Image Width',
                'cgroup' => 'opengraph',
                'key' => 'og_image_width',
                'value' => '1200',
                'locked_by_admin' => 1,
                'created_at' => '2019-10-03 21:01:45',
                'updated_at' => '2019-10-03 21:01:51',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 115,
            ),
            23 => 
            array (
                'id' => 29,
                'title' => 'OpenGraph Image Height',
                'cgroup' => 'opengraph',
                'key' => 'og_image_height',
                'value' => '630',
                'locked_by_admin' => 1,
                'created_at' => '2019-10-03 21:02:21',
                'updated_at' => '2019-10-18 12:36:57',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 116,
            ),
            24 => 
            array (
                'id' => 30,
                'title' => 'OpenGraph Description Max Length',
                'cgroup' => 'opengraph',
                'key' => 'og_descr_max',
                'value' => '300',
                'locked_by_admin' => 1,
                'created_at' => '2019-10-03 21:03:12',
                'updated_at' => '2019-10-03 21:04:54',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 117,
            ),
            25 => 
            array (
                'id' => 31,
                'title' => 'OpenGraph Site Name',
                'cgroup' => 'opengraph',
                'key' => 'og_site_name',
                'value' => 'Firmaq Media',
                'locked_by_admin' => 1,
                'created_at' => '2019-10-18 12:37:44',
                'updated_at' => '2019-10-18 13:31:43',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 118,
            ),
            26 => 
            array (
                'id' => 32,
                'title' => 'Eve Version',
                'cgroup' => 'system',
                'key' => 'lara_eve_version',
                'value' => '1.0.5',
                'locked_by_admin' => 0,
                'created_at' => '2020-08-11 17:09:21',
                'updated_at' => '2020-09-14 10:56:50',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 119,
            ),
            27 => 
            array (
                'id' => 34,
                'title' => 'Top post range days',
                'cgroup' => 'general',
                'key' => 'top_post_range_days',
                'value' => '60',
                'locked_by_admin' => 1,
                'created_at' => '2021-08-05 18:29:35',
                'updated_at' => '2021-08-05 18:31:10',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 121,
            ),
            28 => 
            array (
                'id' => 35,
                'title' => 'Company Facebook Account',
                'cgroup' => 'company',
                'key' => 'company_facebook_account',
                'value' => '#',
                'locked_by_admin' => 1,
                'created_at' => '2023-03-12 13:11:38',
                'updated_at' => '2023-03-12 13:11:40',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 122,
            ),
            29 => 
            array (
                'id' => 36,
                'title' => 'Company Instagram Account',
                'cgroup' => 'company',
                'key' => 'company_instagram_account',
                'value' => '#',
                'locked_by_admin' => 1,
                'created_at' => '2023-03-12 13:12:04',
                'updated_at' => '2023-03-12 13:12:10',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 123,
            ),
            30 => 
            array (
                'id' => 37,
                'title' => 'Company Twitter Account',
                'cgroup' => 'company',
                'key' => 'company_twitter_account',
                'value' => '#',
                'locked_by_admin' => 1,
                'created_at' => '2023-03-12 13:12:46',
                'updated_at' => '2023-03-12 13:12:53',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 124,
            ),
            31 => 
            array (
                'id' => 38,
                'title' => 'Company Linkedin Account',
                'cgroup' => 'company',
                'key' => 'company_linkedin_account',
                'value' => '#',
                'locked_by_admin' => 1,
                'created_at' => '2023-03-12 13:13:23',
                'updated_at' => '2023-03-12 13:13:26',
                'locked_at' => NULL,
                'locked_by' => NULL,
                'position' => 125,
            ),
            32 => 
            array (
                'id' => 39,
                'title' => 'Team Photo Ratio',
                'cgroup' => 'company',
                'key' => 'company_team_photo_ratio',
                'value' => '1x1',
                'locked_by_admin' => 1,
                'created_at' => '2023-03-12 13:13:23',
                'updated_at' => '2023-06-29 14:21:34',
                'locked_at' => '2023-06-29 14:21:34',
                'locked_by' => 2,
                'position' => 126,
            ),
        ));
        
        
    }
}